import type { Ejercicio } from "./tipos";

/* El catálogo: cada patrón de movimiento con sus peldaños, del primero al
   último.

   La idea entera de la calistenia bien hecha está acá: no se sube el peso,
   se sube la dificultad del ejercicio. Una flexión en la pared y una flexión
   con los pies en alto son el mismo movimiento con distinta carga, y esa
   escalera es lo que reemplaza a las mancuernas.

   Por qué esto construye músculo aunque no haya hierro: cuando las series se
   llevan cerca del fallo, la hipertrofia es parecida con cargas altas y con
   cargas bajas. Lo que no se puede es quedarse cómoda: si te sobran cinco
   repeticiones, el peldaño ya te queda chico y toca el siguiente.

   Las repeticiones que aparecen son un rango de trabajo, no una meta sagrada.
   Y el criterio para subir de peldaño está escrito en cada uno. */

export const EJERCICIOS: Ejercicio[] = [
  /* ── Empuje hacia adelante: pecho, hombro, tríceps ─────────────── */
  {
    id: "flexion-pared",
    nombre: "Flexión en la pared",
    patron: "empuje-horizontal",
    nivel: 1,
    equipo: [],
    que: "El primer peldaño del empuje. De pie frente a la pared, casi todo el peso lo sostienen las piernas y los brazos hacen lo poco que pueden hacer todavía.",
    pasos: [
      "De pie frente a una pared, manos a la altura del pecho, un poco más anchas que los hombros.",
      "Da un paso atrás hasta quedar inclinada, con el cuerpo en una sola línea de la cabeza a los talones.",
      "Dobla los codos y acerca el pecho a la pared, con los codos a unos 45 grados del cuerpo, no abiertos en cruz.",
      "Empuja la pared hasta estirar los brazos, sin encoger los hombros hacia las orejas.",
    ],
    errores: [
      "Sacar la cabeza adelante y dejar la cadera atrás: el cuerpo tiene que moverse de una pieza.",
      "Los codos en cruz, apuntando a los lados. Duele el hombro y trabaja menos.",
    ],
    series: 3,
    repes: [10, 20],
    criterio: "Tres series de 20 repeticiones con el cuerpo en línea y sin aguantar la respiración.",
    figura: "flexion_pared",
  },
  {
    id: "flexion-inclinada-alta",
    nombre: "Flexión en la encimera",
    tambien: "inclinada alta",
    patron: "empuje-horizontal",
    nivel: 2,
    equipo: ["mesa"],
    que: "Lo mismo, con las manos más abajo: mientras más baja la superficie, más peso cae sobre los brazos. Esta escalera —pared, encimera, mesa, silla, suelo— es el aumento de carga.",
    pasos: [
      "Manos en la encimera o en una mesa firme, a la anchura de los hombros.",
      "Camina los pies hacia atrás hasta quedar en línea recta, con el abdomen firme.",
      "Baja el pecho hacia la mesa controlando la bajada, en unos dos segundos.",
      "Empuja hasta arriba y separa un poco los omóplatos al final.",
    ],
    errores: [
      "Bajar solo la cabeza en vez de todo el tronco.",
      "Apoyarse en algo con ruedas. Suena obvio hasta que pasa.",
    ],
    series: 3,
    repes: [8, 15],
    criterio: "Tres series de 15 repeticiones limpias.",
    figura: "flexion_inclinada_alta",
  },
  {
    id: "flexion-inclinada-baja",
    nombre: "Flexión en la silla",
    tambien: "inclinada baja",
    patron: "empuje-horizontal",
    nivel: 3,
    equipo: ["silla"],
    que: "El siguiente peldaño: la silla o el borde del sofá, con las manos a unos 45 centímetros del suelo.",
    pasos: [
      "Manos en el asiento de una silla estable apoyada contra la pared, o en un escalón.",
      "Cuerpo en línea, mirada un palmo por delante de las manos.",
      "Baja hasta que el pecho casi toque, con los codos a 45 grados.",
      "Sube empujando el suelo lejos de ti.",
    ],
    errores: [
      "Silla con ruedas o que se desliza: apóyala contra la pared.",
      "Dejar caer la cadera. Aprieta glúteos como si fuera una plancha que se mueve.",
    ],
    series: 3,
    repes: [8, 15],
    criterio: "Tres series de 15 repeticiones bajando en dos segundos.",
    figura: "flexion_inclinada_baja",
  },
  {
    id: "flexion-rodillas",
    nombre: "Flexión con rodillas apoyadas",
    patron: "empuje-horizontal",
    nivel: 4,
    equipo: [],
    que: "Ya en el suelo, con las rodillas como punto de apoyo. Sirve si la flexión completa todavía no sale, siempre que el cuerpo vaya recto de la cabeza a las rodillas.",
    pasos: [
      "Boca abajo, manos bajo los hombros o un poco más anchas, rodillas apoyadas y tobillos cruzados.",
      "Empuja hasta arriba: el cuerpo tiene que ir recto desde la cabeza hasta las rodillas, no sentada sobre los talones.",
      "Baja en dos segundos hasta que el pecho quede a un puño del suelo.",
      "Sube empujando, sin arquear la espalda baja.",
    ],
    errores: [
      "Quedar con la cadera doblada: eso quita la mitad del trabajo.",
      "Bajar medio recorrido. El rango completo construye más músculo que el rango corto.",
    ],
    series: 3,
    repes: [6, 12],
    criterio: "Tres series de 12 repeticiones con el cuerpo recto.",
    cuidado: "Si las muñecas molestan, apoya los puños o usa unos mangos.",
    figura: "flexion_rodillas",
  },
  {
    id: "flexion-completa",
    nombre: "Flexión completa",
    patron: "empuje-horizontal",
    nivel: 5,
    equipo: [],
    que: "La de verdad. Es el ejercicio que más mujeres creen que no van a poder hacer nunca, y casi todas la consiguen subiendo esta escalera peldaño a peldaño.",
    pasos: [
      "En plancha alta, manos bajo los hombros, cuerpo en una línea de la cabeza a los talones.",
      "Aprieta glúteos y abdomen: la flexión es una plancha que sube y baja.",
      "Baja en dos segundos hasta que el pecho quede a un puño del suelo.",
      "Empuja hasta estirar del todo.",
    ],
    errores: [
      "La cadera adelantándose al pecho.",
      "Los codos abiertos en cruz: a 45 grados el hombro sufre menos.",
    ],
    series: 3,
    repes: [5, 12],
    criterio: "Tres series de 12 repeticiones. De ahí se pasa a elevar los pies.",
    figura: "flexion_completa",
  },
  {
    id: "flexion-declinada",
    nombre: "Flexión con los pies en alto",
    patron: "empuje-horizontal",
    nivel: 6,
    equipo: ["silla"],
    que: "Con los pies en una silla cae más peso sobre los brazos y el hombro trabaja más arriba. Es el mismo movimiento, más pesado.",
    pasos: [
      "Pies en una silla o el sofá, manos en el suelo bajo los hombros.",
      "Cuerpo en línea, sin dejar caer la cadera ni levantarla.",
      "Baja controlando hasta que el pecho quede cerca del suelo.",
      "Empuja hasta arriba.",
    ],
    errores: ["Levantar la cadera para hacerla más fácil.", "Perder la línea del cuello."],
    series: 3,
    repes: [5, 12],
    criterio: "Tres series de 12. Después: flexión diamante, o a un brazo asistida.",
    figura: "flexion_declinada",
  },
  {
    id: "flexion-diamante",
    nombre: "Flexión diamante",
    patron: "empuje-horizontal",
    nivel: 7,
    equipo: [],
    que: "Manos juntas bajo el pecho: el tríceps se lleva la mayor parte. De los ejercicios de tríceps con peso corporal, es de los que más activación muestran.",
    pasos: [
      "En plancha alta, junta las manos bajo el pecho formando un triángulo con pulgares e índices.",
      "Codos pegados al cuerpo al bajar.",
      "Baja hasta tocar las manos con el pecho.",
      "Empuja hasta arriba.",
    ],
    errores: ["Abrir los codos: deja de ser diamante.", "Subir la cadera para llegar."],
    series: 3,
    repes: [5, 12],
    cuidado: "Si las muñecas se quejan, abre un poco las manos.",
    figura: "flexion_diamante",
  },

  /* ── Empuje hacia arriba: hombros ──────────────────────────────── */
  {
    id: "press-banda",
    nombre: "Press de hombros con banda",
    patron: "empuje-vertical",
    nivel: 1,
    equipo: ["banda"],
    que: "Empujar por encima de la cabeza, que es el movimiento que más se pierde con los años y el que más falta hace para subir cosas a un estante.",
    pasos: [
      "De pie, pisa el centro de la banda con los dos pies y toma los extremos a la altura de los hombros.",
      "Aprieta glúteos y abdomen para no arquear la espalda.",
      "Empuja hacia arriba hasta estirar los brazos, con las manos terminando sobre la cabeza y no delante.",
      "Baja despacio hasta los hombros.",
    ],
    errores: [
      "Arquear la espalda baja para empujar: si pasa, la banda es demasiado dura.",
      "Empujar hacia adelante en vez de hacia arriba.",
    ],
    series: 3,
    repes: [8, 15],
    criterio: "Tres series de 15 con una banda que en la última cueste de verdad.",
    figura: "press_banda",
  },
  {
    id: "press-mochila",
    nombre: "Press de hombros con mochila",
    patron: "empuje-vertical",
    nivel: 2,
    equipo: ["mochila"],
    que: "Lo mismo con una mochila cargada de libros o botellas de agua. Dos litros pesan dos kilos: es una forma barata de tener pesos que suben de a poco.",
    pasos: [
      "Sujeta la mochila por las asas a la altura del pecho.",
      "Costillas abajo, glúteos apretados.",
      "Empuja por encima de la cabeza hasta estirar los codos.",
      "Baja en dos segundos.",
    ],
    errores: ["Arquear la espalda.", "Encoger los hombros hacia las orejas."],
    series: 3,
    repes: [8, 12],
    criterio: "Tres series de 12. Después: más peso en la mochila, o pasar a la pica.",
    figura: "press_mochila",
  },
  {
    id: "pica-elevada",
    nombre: "Flexión en pica con manos en alto",
    patron: "empuje-vertical",
    nivel: 3,
    equipo: ["silla"],
    que: "La forma de empujar hacia arriba sin ningún peso: se levanta la cadera hasta que el cuerpo forma una V y el empuje pasa a ser casi vertical.",
    pasos: [
      "Manos en una silla, pies en el suelo, cadera bien arriba formando una V invertida.",
      "Baja la coronilla hacia la silla doblando los codos.",
      "Los codos van hacia atrás y afuera, no en cruz.",
      "Empuja hasta estirar.",
    ],
    errores: ["Perder la V y convertirlo en una flexión normal.", "Apoyar la cabeza de golpe."],
    series: 3,
    repes: [6, 12],
    criterio: "Tres series de 12 con la cadera bien alta.",
    figura: "pica_elevada",
  },
  {
    id: "pica-suelo",
    nombre: "Flexión en pica",
    patron: "empuje-vertical",
    nivel: 4,
    equipo: [],
    que: "Igual pero con las manos en el suelo. Es el paso previo real al pino, y ya es un ejercicio de hombro exigente.",
    pasos: [
      "Desde el perro boca abajo del yoga: manos y pies en el suelo, cadera arriba.",
      "Camina los pies hacia las manos hasta que la espalda quede casi vertical.",
      "Baja la coronilla hacia el suelo, entre las manos.",
      "Empuja hasta estirar los brazos.",
    ],
    errores: ["Dejar la cadera baja.", "Bajar la cabeza por delante de las manos."],
    series: 3,
    repes: [5, 10],
    criterio: "Tres series de 10. Después: pies elevados en una silla.",
    figura: "pica_suelo",
  },
  {
    id: "pica-pies-altos",
    nombre: "Flexión en pica con pies en alto",
    patron: "empuje-vertical",
    nivel: 5,
    equipo: ["silla"],
    que: "Con los pies en una silla, el cuerpo queda casi vertical y el hombro carga casi todo el peso. Es lo más parecido a un press militar que se puede hacer sin peso.",
    pasos: [
      "Pies en una silla, manos en el suelo, cadera lo más arriba posible.",
      "Baja la coronilla hacia el suelo, entre las manos.",
      "Empuja hasta estirar del todo.",
      "Mantén el abdomen firme: acá es fácil arquearse.",
    ],
    errores: ["Bajar poco.", "Dejar que la espalda se arquee."],
    series: 3,
    repes: [4, 10],
    cuidado: "Si tienes la presión alta o te marea estar cabeza abajo, quédate en el peldaño anterior.",
    figura: "pica_pies_altos",
  },

  /* ── Tirar hacia el cuerpo: espalda ────────────────────────────── */
  {
    id: "remo-banda",
    nombre: "Remo con banda sentada",
    patron: "traccion-horizontal",
    nivel: 1,
    equipo: ["banda"],
    que: "Tirar es la mitad del cuerpo que casi todos los programas caseros olvidan, y la que arregla la espalda encorvada de estar sentada. Este es el primer peldaño.",
    pasos: [
      "Sentada en el suelo con las piernas estiradas, pasa la banda por las plantas de los pies.",
      "Espalda larga, pecho abierto.",
      "Tira de los extremos hacia las costillas, llevando los codos atrás y juntando los omóplatos.",
      "Suelta despacio, sin dejar que la banda te tire hacia adelante.",
    ],
    errores: [
      "Tirar con los brazos y no con la espalda: piensa en llevar los codos al bolsillo de atrás.",
      "Encorvarse al soltar.",
    ],
    series: 3,
    repes: [10, 15],
    criterio: "Tres series de 15 con una banda que cueste al final.",
    figura: "remo_banda",
  },
  {
    id: "remo-mochila",
    nombre: "Remo inclinada con mochila",
    patron: "traccion-horizontal",
    nivel: 3,
    equipo: ["mochila"],
    que:
      "El remo de toda la vida, con una mochila cargada en vez de una barra. Es el ejercicio de espalda más directo que se puede hacer en casa, y el peso sube cuando quieras: más botellas de agua.",
    pasos: [
      "De pie, pies a la anchura de la cadera, con la mochila en el suelo entre ellos.",
      "Lleva la cadera atrás y baja el tronco hasta casi paralelo al suelo, con la espalda larga y las rodillas algo dobladas.",
      "Sujeta la mochila con las dos manos y tira de ella hacia el ombligo, llevando los codos atrás y pegados al cuerpo.",
      "Bájala en dos segundos sin soltar la espalda.",
    ],
    errores: [
      "Redondear la espalda al inclinarse: si no aguantas la posición, sube un poco el tronco.",
      "Subir el tronco cada vez que tiras. El tronco no se mueve; se mueven los brazos.",
    ],
    series: 3,
    repes: [8, 15],
    criterio: "Tres series de 15 con toda la carga que le quepa a la mochila.",
    cuidado: "Si la espalda baja se queja, apoya una mano en una silla y hazlo a un brazo.",
    figura: "remo_mochila",
  },
  {
    id: "remo-mochila-una-mano",
    nombre: "Remo a una mano con mochila",
    patron: "traccion-horizontal",
    nivel: 4,
    equipo: ["mochila", "silla"],
    que:
      "Con una mano apoyada, toda la carga cae en un lado y la espalda baja descansa. Es el peldaño donde se puede cargar más peso sin que la técnica se pierda.",
    pasos: [
      "Apoya una mano y una rodilla en el asiento de una silla, con el otro pie en el suelo.",
      "Espalda plana y paralela al suelo, como una mesa.",
      "Con la mano libre, tira de la mochila desde el suelo hasta la cadera, con el codo pegado al cuerpo.",
      "Baja en dos segundos hasta estirar el brazo del todo.",
    ],
    errores: [
      "Girar el tronco para ayudarse. Los dos hombros quedan a la misma altura.",
      "Separar el codo del cuerpo: así trabaja el hombro y no la espalda.",
    ],
    series: 3,
    repes: [6, 12],
    figura: "remo_mochila_una_mano",
  },


  /* ── Sentadilla ────────────────────────────────────────────────── */
  {
    id: "sentadilla-silla",
    nombre: "Sentarse y levantarse",
    patron: "sentadilla",
    nivel: 1,
    equipo: ["silla"],
    que: "El primer peldaño y, a la vez, la prueba de vida que usan los geriatras: levantarse de una silla sin manos es lo que decide si alguien vive sola a los ochenta.",
    pasos: [
      "Siéntate al borde de una silla, pies a la anchura de la cadera.",
      "Sin usar las manos, inclina un poco el tronco y levántate empujando el suelo.",
      "Arriba, aprieta los glúteos y estírate del todo.",
      "Baja controlando hasta rozar la silla: no te dejes caer.",
    ],
    errores: [
      "Dejarse caer de golpe en la silla. La bajada es la mitad del ejercicio.",
      "Impulsarse con los brazos.",
    ],
    series: 3,
    repes: [10, 20],
    criterio: "Tres series de 20 sin manos y bajando en dos segundos.",
    figura: "sentadilla_silla",
  },
  {
    id: "sentadilla",
    nombre: "Sentadilla",
    patron: "sentadilla",
    nivel: 2,
    equipo: [],
    que: "Sin silla, bajando todo lo que la cadera permita. Cuanto más abajo, más trabaja el glúteo: el rango completo construye más músculo que el rango corto.",
    pasos: [
      "Pies a la anchura de los hombros, puntas un poco hacia afuera.",
      "Baja llevando la cadera atrás y abajo, con el pecho arriba y los talones pegados al suelo.",
      "Baja hasta que los muslos pasen la paralela, si tu cadera lo permite sin que la espalda se redondee.",
      "Sube empujando el suelo y aprieta los glúteos arriba.",
    ],
    errores: [
      "Levantar los talones: si pasa, separa un poco más los pies o ponte unos zapatos con algo de tacón.",
      "Que las rodillas se caigan hacia dentro. Ábrelas hacia donde apuntan los pies.",
    ],
    series: 3,
    repes: [10, 20],
    criterio: "Tres series de 20 profundas. Después: una pierna, o peso.",
    figura: "sentadilla",
  },
  {
    id: "sentadilla-mochila",
    nombre: "Sentadilla con mochila",
    patron: "sentadilla",
    nivel: 3,
    equipo: ["mochila"],
    que: "Las piernas se acostumbran rápido al peso del cuerpo. La mochila es la forma más simple de seguir subiendo la carga en casa.",
    pasos: [
      "Ponte la mochila cargada en la espalda, o abrázala contra el pecho.",
      "Sentadilla igual que antes, con el peso pegado al cuerpo.",
      "Baja en dos segundos, sube empujando.",
      "Si la llevas delante, el tronco trabaja más.",
    ],
    errores: ["Cargar tanto que se pierda la forma.", "Redondear la espalda al bajar."],
    series: 3,
    repes: [8, 15],
    figura: "sentadilla_mochila",
  },
  {
    id: "sentadilla-bulgara",
    nombre: "Sentadilla búlgara",
    patron: "sentadilla",
    nivel: 4,
    equipo: ["silla"],
    que: "Un pie atrás sobre una silla: casi todo el peso cae en la pierna de adelante. Es de los ejercicios de pierna más duros que se pueden hacer sin equipo, y de los mejores para glúteo.",
    pasos: [
      "De espaldas a una silla, apoya el empeine de un pie en el asiento.",
      "El pie de adelante, a un paso largo por delante.",
      "Baja la rodilla de atrás hacia el suelo, con el tronco un poco inclinado adelante si quieres más glúteo.",
      "Sube empujando con el talón de adelante.",
    ],
    errores: [
      "El pie de adelante demasiado cerca: la rodilla se va muy adelante y molesta.",
      "Perder el equilibrio por ir rápido. Apóyate en la pared con una mano al principio.",
    ],
    series: 3,
    repes: [6, 12],
    criterio: "Tres series de 12 por pierna.",
    cuidado: "Si la rodilla de adelante se queja, aleja el pie y baja menos.",
    figura: "sentadilla_bulgara",
  },
  {
    id: "pistol-silla",
    nombre: "Sentadilla a una pierna, a la silla",
    patron: "sentadilla",
    nivel: 5,
    equipo: ["silla"],
    que: "Sentarse y levantarse con una sola pierna. Es el camino hacia la sentadilla a una pierna completa, y ya por sí sola es muy exigente.",
    pasos: [
      "Siéntate al borde de la silla, estira una pierna al frente.",
      "Levántate empujando con la pierna apoyada, sin impulso de brazos.",
      "Baja despacio con la misma pierna hasta rozar la silla.",
      "Si no sale, usa una silla más alta o ayúdate con un dedo en la pared.",
    ],
    errores: ["Tomar impulso con el tronco.", "Dejarse caer en la bajada."],
    series: 3,
    repes: [3, 8],
    figura: "pistol_silla",
  },

  /* ── Cadera y glúteo ───────────────────────────────────────────── */
  {
    id: "puente",
    nombre: "Puente de glúteo",
    patron: "bisagra",
    nivel: 1,
    equipo: [],
    que: "El primer peldaño de la cadera. Trabaja el glúteo sin cargar la espalda baja y es lo que mejor entra cuando se lleva mucho tiempo sentada.",
    pasos: [
      "Boca arriba, rodillas dobladas, pies a la anchura de la cadera y cerca de los glúteos.",
      "Empuja con los talones y sube la cadera hasta formar una línea de las rodillas a los hombros.",
      "Aprieta los glúteos arriba un segundo. No busques subir más arqueando la espalda.",
      "Baja en dos segundos sin apoyar del todo.",
    ],
    errores: [
      "Subir con la espalda baja en vez de con el glúteo: si lo sientes en la lumbar, mete un poco la pelvis antes de subir.",
      "Pies demasiado lejos: entonces trabaja el isquio y no el glúteo.",
    ],
    series: 3,
    repes: [12, 20],
    criterio: "Tres series de 20 apretando arriba.",
    figura: "puente",
  },
  {
    id: "puente-una-pierna",
    nombre: "Puente a una pierna",
    patron: "bisagra",
    nivel: 2,
    equipo: [],
    que: "El mismo movimiento con una sola pierna: el doble de carga sin ningún peso, y además obliga a la cadera a no irse de lado.",
    pasos: [
      "Boca arriba, un pie apoyado y la otra rodilla abrazada al pecho o la pierna estirada.",
      "Empuja con el talón apoyado y sube la cadera.",
      "Las dos caderas a la misma altura: no dejes que caiga la del lado libre.",
      "Baja despacio.",
    ],
    errores: ["Que la cadera se venza de un lado.", "Impulsarse con la pierna libre."],
    series: 3,
    repes: [8, 15],
    criterio: "Tres series de 15 por pierna con la cadera nivelada.",
    figura: "puente_una_pierna",
  },
  {
    id: "empuje-sofa",
    nombre: "Empuje de cadera en el sofá",
    tambien: "hip thrust",
    patron: "bisagra",
    nivel: 3,
    equipo: ["silla"],
    que: "Con los hombros apoyados en el sofá, el glúteo trabaja en el rango donde más fuerza puede hacer. Es el ejercicio con más activación de glúteo que se ha medido.",
    pasos: [
      "Siéntate en el suelo con la espalda alta apoyada en el borde del sofá.",
      "Pies a la anchura de la cadera, rodillas a 90 grados cuando estés arriba.",
      "Empuja con los talones y sube la cadera hasta que el tronco quede horizontal.",
      "Barbilla metida, mirada al frente. Aprieta arriba un segundo.",
    ],
    errores: [
      "Arquear la espalda arriba en vez de estirar la cadera.",
      "Sofá que se resbala: apóyalo contra la pared.",
    ],
    series: 3,
    repes: [10, 20],
    criterio: "Tres series de 20. Después: con mochila encima, o a una pierna.",
    figura: "empuje_sofa",
  },
  {
    id: "empuje-sofa-peso",
    nombre: "Empuje de cadera con peso",
    patron: "bisagra",
    nivel: 4,
    equipo: ["silla", "mochila"],
    que: "El mismo empuje con una mochila cargada apoyada sobre la cadera. Es, de todo lo que hay en casa, lo que más carga admite el glúteo.",
    pasos: [
      "Igual que el anterior, con la mochila apoyada sobre los pliegues de la cadera.",
      "Sujétala con las manos.",
      "Sube hasta estirar la cadera del todo.",
      "Baja en dos segundos.",
    ],
    errores: ["Poner el peso sobre el vientre y no sobre la cadera.", "Rango corto."],
    series: 3,
    repes: [8, 15],
    figura: "empuje_sofa_peso",
  },
  {
    id: "peso-muerto-una-pierna",
    nombre: "Bisagra a una pierna",
    tambien: "peso muerto rumano a una pierna",
    patron: "bisagra",
    nivel: 5,
    equipo: [],
    que: "El movimiento de agacharse a recoger algo, que es el que más se lesiona cuando no se entrena. Trabaja isquiotibiales, glúteo y todo el equilibrio.",
    pasos: [
      "De pie sobre una pierna, la otra un poco atrás.",
      "Con la espalda larga, lleva la cadera atrás y baja el tronco mientras la pierna libre sube detrás.",
      "Baja hasta sentir el estiramiento en la parte de atrás del muslo, sin redondear la espalda.",
      "Sube apretando el glúteo.",
    ],
    errores: [
      "Redondear la espalda: el movimiento es de la cadera, no de la columna.",
      "Abrir la cadera de lado. Las dos caderas miran al suelo.",
    ],
    series: 3,
    repes: [6, 12],
    cuidado: "Si el equilibrio falla, apoya dos dedos en la pared. No es hacer trampa.",
    figura: "peso_muerto_una_pierna",
  },
  {
    id: "curl-nordico",
    nombre: "Curl nórdico asistido",
    patron: "bisagra",
    nivel: 6,
    equipo: [],
    que: "Bajar el cuerpo hacia adelante desde las rodillas, frenando con los isquiotibiales. Es el ejercicio con más evidencia para prevenir lesiones de isquiotibiales, y es durísimo.",
    pasos: [
      "De rodillas sobre algo blando, con los tobillos sujetos bajo un sofá o por alguien.",
      "Cuerpo recto de las rodillas a la cabeza.",
      "Baja hacia adelante lo más lento que puedas, frenando con la parte de atrás del muslo.",
      "Cuando ya no puedas frenar, cae sobre las manos y empuja para volver.",
    ],
    errores: ["Doblar la cadera para hacerlo más fácil.", "Hacer demasiadas: con tres o cinco basta."],
    series: 3,
    repes: [3, 6],
    cuidado: "Deja bastante agujetas los primeros días. Empieza con una sola serie.",
    figura: "curl_nordico",
  },

  /* ── Una pierna ────────────────────────────────────────────────── */
  {
    id: "zancada-estatica",
    nombre: "Zancada estática",
    patron: "zancada",
    nivel: 1,
    equipo: [],
    que: "Un pie adelante, uno atrás, y se sube y se baja en el sitio. Sin el equilibrio de caminar, es el primer peldaño del trabajo de una pierna.",
    pasos: [
      "Un pie un paso largo por delante del otro, talón de atrás levantado.",
      "Baja recto hacia el suelo, doblando las dos rodillas.",
      "La rodilla de atrás casi toca el suelo.",
      "Sube empujando con el talón de adelante.",
    ],
    errores: ["Inclinarse hacia adelante.", "Pasos demasiado cortos: la rodilla se adelanta mucho."],
    series: 3,
    repes: [8, 15],
    criterio: "Tres series de 15 por pierna.",
    figura: "zancada_estatica",
  },
  {
    id: "zancada-atras",
    nombre: "Zancada hacia atrás",
    patron: "zancada",
    nivel: 2,
    equipo: [],
    que: "Se da el paso hacia atrás, lo que carga menos la rodilla de adelante que la zancada hacia adelante. Para rodillas quisquillosas, es la buena.",
    pasos: [
      "De pie, da un paso largo hacia atrás.",
      "Baja hasta que la rodilla de atrás casi toque.",
      "Empuja con el talón de adelante para volver a juntar los pies.",
      "Alterna piernas.",
    ],
    errores: ["Dar el paso muy corto.", "Dejar caer el tronco."],
    series: 3,
    repes: [8, 12],
    figura: "zancada_atras",
  },
  {
    id: "subida-escalon",
    nombre: "Subida al escalón",
    patron: "zancada",
    nivel: 3,
    equipo: ["escalon"],
    que: "Subir a un escalón alto con una pierna. Es lo más parecido a subir escaleras cargada, que es exactamente para lo que sirve.",
    pasos: [
      "Pon un pie entero sobre un escalón o una silla firme, a la altura de la rodilla si puedes.",
      "Sube empujando solo con esa pierna, sin impulsarte con la de abajo.",
      "Arriba, estírate del todo.",
      "Baja despacio con la misma pierna.",
    ],
    errores: [
      "Rebotar con el pie de abajo para impulsarse: ese es el error que lo convierte en otra cosa.",
      "Dejarse caer al bajar.",
    ],
    series: 3,
    repes: [6, 12],
    criterio: "Tres series de 12 por pierna sin impulso. Después: con mochila.",
    figura: "subida_escalon",
  },
  {
    id: "subida-escalon-peso",
    nombre: "Subida al escalón con peso",
    patron: "zancada",
    nivel: 4,
    equipo: ["escalon", "mochila"],
    que: "Lo mismo con la mochila cargada. Sube la carga sin tener que cambiar de ejercicio.",
    pasos: [
      "Mochila a la espalda o abrazada al pecho.",
      "Sube con una pierna, sin impulso.",
      "Estírate arriba.",
      "Baja en dos segundos.",
    ],
    errores: ["Perder el control al bajar.", "Escalón que se mueve."],
    series: 3,
    repes: [6, 12],
    figura: "subida_escalon_peso",
  },

  /* ── Centro: no arquearse ──────────────────────────────────────── */
  {
    id: "bicho-muerto",
    nombre: "Bicho muerto",
    tambien: "dead bug",
    patron: "core-antiextension",
    nivel: 1,
    equipo: [],
    que: "Boca arriba, moviendo brazos y piernas sin que la espalda se despegue del suelo. Enseña lo único que el abdomen tiene que aprender: sostener la columna quieta mientras todo lo demás se mueve.",
    pasos: [
      "Boca arriba, brazos al techo y rodillas dobladas en el aire, a 90 grados.",
      "Pega la espalda baja al suelo y no la sueltes en toda la serie.",
      "Estira a la vez un brazo hacia atrás y la pierna contraria hacia adelante.",
      "Vuelve despacio y cambia de lado.",
    ],
    errores: [
      "Que la espalda baja se despegue del suelo: si pasa, baja menos la pierna.",
      "Aguantar la respiración. Suelta el aire al estirar.",
    ],
    series: 3,
    repes: [8, 16],
    criterio: "Tres series de 16 con la espalda pegada al suelo todo el rato.",
    figura: "bicho_muerto",
  },
  {
    id: "plancha-rodillas",
    nombre: "Plancha de rodillas",
    patron: "core-antiextension",
    nivel: 2,
    equipo: [],
    que: "La plancha con las rodillas apoyadas. Lo importante no es aguantar mucho: es que la línea del cuerpo no se rompa.",
    pasos: [
      "Antebrazos en el suelo, codos bajo los hombros, rodillas apoyadas.",
      "Cuerpo recto de la cabeza a las rodillas.",
      "Aprieta glúteos y mete un poco la pelvis.",
      "Respira normal.",
    ],
    errores: ["Sacar el trasero hacia arriba.", "Dejar caer la lumbar."],
    series: 3,
    repes: [20, 45],
    porTiempo: true,
    criterio: "Tres veces 45 segundos sin perder la línea.",
    figura: "plancha_rodillas",
  },
  {
    id: "plancha",
    nombre: "Plancha",
    patron: "core-antiextension",
    nivel: 3,
    equipo: [],
    que: "Con los pies apoyados. Más de un minuto no aporta gran cosa: cuando ya aguantas ese minuto, conviene hacerla más difícil y no más larga.",
    pasos: [
      "Antebrazos en el suelo, codos bajo los hombros, pies a la anchura de la cadera.",
      "Cuerpo en una línea de la cabeza a los talones.",
      "Aprieta glúteos y abdomen, mete un poco la pelvis.",
      "Respira. No aguantes el aire.",
    ],
    errores: ["Subir la cadera para descansar.", "Aguantar minutos con la espalda hundida."],
    series: 3,
    repes: [20, 60],
    porTiempo: true,
    criterio: "Tres veces 60 segundos limpias. Después: con toque de hombro.",
    figura: "plancha",
  },
  {
    id: "plancha-toque",
    nombre: "Plancha con toque de hombro",
    patron: "core-antiextension",
    nivel: 4,
    equipo: [],
    que: "En plancha alta, tocándose un hombro con la mano contraria. Al quitar un apoyo, el centro tiene que impedir que la cadera gire: es bastante más duro de lo que parece.",
    pasos: [
      "Plancha alta, manos bajo los hombros, pies algo separados.",
      "Levanta una mano y tócate el hombro contrario.",
      "La cadera no se mueve ni un centímetro.",
      "Alterna despacio.",
    ],
    errores: ["Que la cadera bascule en cada toque.", "Ir rápido."],
    series: 3,
    repes: [10, 20],
    figura: "plancha_toque",
  },
  {
    id: "rodillo",
    nombre: "Rodillo desde rodillas",
    tambien: "ab wheel",
    patron: "core-antiextension",
    nivel: 5,
    equipo: [],
    que: "Deslizarse hacia adelante con las manos sobre un trapo o una rueda, frenando con el abdomen. Es de los ejercicios de centro más exigentes que existen.",
    pasos: [
      "De rodillas, manos sobre dos trapos en un suelo liso, o sobre una rueda.",
      "Mete la pelvis y aprieta el abdomen antes de empezar.",
      "Desliza las manos hacia adelante todo lo que puedas sin que la espalda se arquee.",
      "Vuelve tirando con el abdomen, no con los brazos.",
    ],
    errores: [
      "Llegar más lejos de lo que el abdomen aguanta: se nota porque duele la lumbar.",
      "Empezar con el rango completo.",
    ],
    series: 3,
    repes: [4, 10],
    cuidado: "Nada de esto si hay dolor lumbar o diástasis sin revisar.",
    figura: "rodillo",
  },

  /* ── Centro: los costados ──────────────────────────────────────── */
  {
    id: "plancha-lateral-rodillas",
    nombre: "Plancha lateral de rodillas",
    patron: "core-lateral",
    nivel: 1,
    equipo: [],
    que: "De lado, apoyada en el antebrazo y las rodillas. Trabaja oblicuos y glúteo medio, que es el que sostiene la cadera al caminar.",
    pasos: [
      "De lado, codo bajo el hombro, rodillas dobladas y apoyadas.",
      "Sube la cadera hasta formar una línea de la cabeza a las rodillas.",
      "No dejes que el hombro de abajo se hunda.",
      "Respira normal.",
    ],
    errores: ["Rotar el pecho hacia el suelo.", "Cadera baja."],
    series: 2,
    repes: [15, 40],
    porTiempo: true,
    criterio: "Dos veces 40 segundos por lado.",
    figura: "plancha_lateral_rodillas",
  },
  {
    id: "plancha-lateral",
    nombre: "Plancha lateral",
    patron: "core-lateral",
    nivel: 2,
    equipo: [],
    que: "Con los pies apoyados. Es de los ejercicios que menos carga la columna para lo mucho que trabaja el costado.",
    pasos: [
      "De lado, codo bajo el hombro, pies uno delante del otro o apilados.",
      "Sube la cadera y haz una línea recta de la cabeza a los pies.",
      "El brazo de arriba al techo o en la cadera.",
      "Respira.",
    ],
    errores: ["Dejar caer la cadera.", "Girar el tronco."],
    series: 2,
    repes: [20, 45],
    porTiempo: true,
    criterio: "Dos veces 45 segundos por lado. Después: con elevaciones de cadera.",
    figura: "plancha_lateral",
  },
  {
    id: "maleta",
    nombre: "Caminar con peso a un lado",
    tambien: "transporte de maleta",
    patron: "core-lateral",
    nivel: 3,
    equipo: ["mochila"],
    que: "Cargar algo pesado con una mano y caminar sin inclinarse. Entrena el agarre, el costado y la postura a la vez, y es exactamente lo que haces con la compra.",
    pasos: [
      "Carga una bolsa o mochila pesada con una mano.",
      "Camina despacio, con los hombros nivelados y el tronco recto.",
      "No te inclines hacia el lado libre.",
      "Cambia de mano y vuelve.",
    ],
    errores: ["Inclinarse para compensar.", "Encoger el hombro cargado."],
    series: 3,
    repes: [20, 45],
    porTiempo: true,
    figura: "maleta",
  },

  /* ── Hombros sanos ─────────────────────────────────────────────── */
  {
    id: "aperturas-banda",
    nombre: "Aperturas con banda",
    tambien: "band pull-apart",
    patron: "escapulas",
    nivel: 1,
    equipo: ["banda"],
    que: "Lo que compensa las horas de teléfono y de escritorio. Es barato, rápido y es lo que hace que empujar y tirar no terminen en un hombro dolorido.",
    pasos: [
      "De pie, sujeta una banda con las dos manos, brazos estirados al frente a la altura del pecho.",
      "Abre los brazos hacia los lados juntando los omóplatos.",
      "Llega hasta donde puedas sin encoger los hombros.",
      "Vuelve despacio.",
    ],
    errores: ["Subir los hombros hacia las orejas.", "Arquear la espalda."],
    series: 2,
    repes: [12, 20],
    figura: "aperturas_banda",
  },
  {
    id: "ytw",
    nombre: "Y-T-W boca abajo",
    patron: "escapulas",
    nivel: 2,
    equipo: [],
    que: "Tumbada boca abajo, levantando los brazos en tres formas distintas. Trabaja la parte de atrás del hombro y la espalda alta sin nada de equipo.",
    pasos: [
      "Boca abajo, frente apoyada, brazos estirados adelante formando una Y.",
      "Levanta los brazos unos centímetros y bájalos: diez veces.",
      "Ahora en cruz, formando una T: diez veces.",
      "Ahora con los codos doblados junto a las costillas, formando una W: diez veces.",
    ],
    errores: ["Levantar la cabeza.", "Usar impulso: sube poco y despacio."],
    series: 2,
    repes: [8, 12],
    figura: "ytw",
  },

  /* ── Pantorrillas ──────────────────────────────────────────────── */
  {
    id: "talones",
    nombre: "Elevación de talones",
    patron: "pantorrilla",
    nivel: 1,
    equipo: [],
    que: "La pantorrilla se olvida siempre y es la que sostiene el tobillo, que es lo que evita los tropiezos con los años.",
    pasos: [
      "De pie, apoya dos dedos en la pared para el equilibrio.",
      "Sube los talones todo lo que puedas.",
      "Aguanta un segundo arriba.",
      "Baja despacio hasta el suelo.",
    ],
    errores: ["Rebotar.", "Rango corto."],
    series: 3,
    repes: [15, 25],
    criterio: "Tres series de 25. Después: a una pierna.",
    figura: "talones",
  },
  {
    id: "talones-una-pierna",
    nombre: "Elevación de talón a una pierna",
    patron: "pantorrilla",
    nivel: 2,
    equipo: ["escalon"],
    que: "Sobre un escalón, con el talón cayendo por debajo: el rango completo es lo que hace que la pantorrilla crezca.",
    pasos: [
      "De pie sobre el borde de un escalón con la punta de un pie.",
      "Deja caer el talón por debajo del escalón.",
      "Sube todo lo que puedas y aguanta un segundo.",
      "Baja despacio.",
    ],
    errores: ["No bajar el talón del todo.", "Ayudarse con la otra pierna."],
    series: 3,
    repes: [8, 20],
    figura: "talones_una_pierna",
  },
];

/** Los ejercicios de un patrón, del primer peldaño al último. */
export function escalera(patron: string) {
  return EJERCICIOS.filter((e) => e.patron === patron).sort((a, b) => a.nivel - b.nivel);
}

export function porId(id: string) {
  return EJERCICIOS.find((e) => e.id === id);
}
