import type { Paso } from "./tipos";

/* Catálogo de posturas.

   EL ORDEN DE ESTE ARRAY, dentro de cada fase, ES EL ORDEN DE LA PRÁCTICA.
   No se reordena al armar: lo único que hace el armado es sacar lo que no
   viene al caso y ajustar cuánto dura cada cosa. Esto importa porque una
   clase tiene un arco — se calienta antes de exigir, se abre antes de torcer,
   y se baja antes de descansar.

   Qué dice cada campo y de dónde sale:
   · `trabaja` describe lo que la postura hace mecánicamente (qué articulación
     se mueve, qué músculo se alarga). Eso es anatomía, no un efecto clínico.
     Lo que hay probado por objetivo está en `evidencia.ts`, con su estudio.
   · `evita` son las contraindicaciones reales que sacan la postura de la
     rutina sola. Las de presión ocular, cuello, osteoporosis y embarazo son
     las que más importan y están citadas en la biblioteca.
   · `nivel` 1 accesible · 2 intermedia · 3 exigente.
   · `carga` 1 descanso · 2 trabajo · 3 fuerte. El armado usa esto para no
     pasarse de la intensidad que se pidió.
*/

export const POSTURAS: Paso[] = [
  // ══ Calentar ═══════════════════════════════════════════════
  {
    id: "cal-gato-vaca",
    fase: "calentamiento",
    nombre: "Gato y vaca",
    sanscrito: "Marjaryasana / Bitilasana",
    familia: "cuadrupedia",
    segundos: 60,
    minimo: 40,
    maximo: 120,
    nivel: 1,
    carga: 1,
    estilos: [],
    objetivos: ["espalda", "postura", "cuello_hombros", "energia"],
    trabaja:
      "Mueve la columna entre flexión y extensión, vértebra por vértebra. Es lo primero que se hace porque pone en marcha todo el eje antes de exigirle.",
    como: [
      "Apóyate en manos y rodillas: manos bajo los hombros, rodillas bajo las caderas.",
      "Al inhalar, deja caer la panza y abre el pecho adelante.",
      "Al exhalar, redondea la espalda y lleva el mentón al pecho.",
      "Sigue el ritmo de tu respiración, sin apurar.",
    ],
    respirar: "Inhala al abrir, exhala al redondear. Un ciclo por respiración.",
    mejoraCon: ["manta"],
    evita: ["munecas", "rodillas"],
    masFacil: "Si las muñecas molestan, hazlo sentada en una silla, con las manos en los muslos.",
    base: true,
    prioridad: 1,
    figura: "gato",
    formas: [
      { figura: "vaca", texto: "Inhala: la panza baja, el pecho se abre" },
      { figura: "gato", texto: "Exhala: la espalda se redondea" },
    ],
    fuente: "Movilidad segmentaria de columna — instrucción clásica de hatha",
  },
  {
    id: "cal-hombros-circulos",
    fase: "calentamiento",
    nombre: "Círculos de hombros",
    familia: "sentada",
    segundos: 45,
    minimo: 30,
    maximo: 70,
    nivel: 1,
    carga: 1,
    estilos: ["silla", "somatico"],
    objetivos: ["cuello_hombros", "postura", "pecho"],
    trabaja:
      "Lleva el hombro por todo su recorrido y despega la escápula, que es lo que queda pegado después de horas de teclado.",
    como: [
      "Sentada o de pie, brazos sueltos a los lados.",
      "Sube los hombros hacia las orejas, llévalos atrás y déjalos caer.",
      "Cinco vueltas hacia atrás y cinco hacia adelante, lentas.",
    ],
    respirar: "Inhala al subir, exhala al soltar.",
    prioridad: 2,
    figura: "sentada",
  },
  {
    id: "cal-cuello",
    fase: "calentamiento",
    nombre: "Soltar el cuello",
    familia: "sentada",
    segundos: 60,
    minimo: 40,
    maximo: 90,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["silla", "somatico", "iyengar"],
    objetivos: ["cuello_hombros", "calma", "postura"],
    trabaja:
      "Alarga el trapecio superior y el elevador de la escápula, los dos que se acortan cuando la cabeza vive adelantada frente a la pantalla.",
    como: [
      "Sentada, espalda larga, hombros abajo.",
      "Lleva la oreja derecha al hombro derecho, sin girar la cara.",
      "Si quieres más, deja caer el peso de la mano derecha sobre la cabeza. Nada de tirar.",
      "Vuelve al centro y cambia de lado.",
    ],
    cuidado: "Nunca hagas círculos completos con la cabeza hacia atrás: comprime las cervicales.",
    respirar: "Respira normal, tres o cuatro veces por lado.",
    evita: ["cuello"],
    prioridad: 2,
    figura: "cuello_lateral",
  },
  {
    id: "cal-cadera-circulos",
    fase: "calentamiento",
    nombre: "Círculos de cadera",
    familia: "cuadrupedia",
    segundos: 60,
    minimo: 40,
    maximo: 90,
    nivel: 1,
    carga: 1,
    estilos: ["somatico", "vinyasa"],
    objetivos: ["caderas", "espalda", "energia"],
    trabaja: "Lubrica la cadera en su rango completo y despierta el glúteo profundo antes de pedirle rango.",
    como: [
      "En cuatro apoyos, dibuja círculos grandes con la pelvis, como si revolvieras una olla.",
      "Cinco vueltas para un lado, cinco para el otro.",
      "Deja que la columna acompañe el movimiento.",
    ],
    mejoraCon: ["manta"],
    evita: ["munecas", "rodillas"],
    prioridad: 3,
    figura: "cuadrupedia",
    formas: [
      { figura: "cuadrupedia", texto: "Adelante: hombros sobre las manos" },
      { figura: "cadera_atras", texto: "Atrás: la cadera hacia los talones" },
    ],
  },
  {
    id: "cal-aguja",
    fase: "calentamiento",
    nombre: "Hilo en la aguja",
    sanscrito: "Parsva Balasana",
    familia: "cuadrupedia",
    segundos: 60,
    minimo: 45,
    maximo: 150,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "yin"],
    objetivos: ["cuello_hombros", "postura", "pecho"],
    trabaja:
      "Rota la columna dorsal — la parte de la espalda que casi no gira cuando se está sentada — y estira la parte de atrás del hombro.",
    como: [
      "En cuatro apoyos, desliza el brazo derecho por debajo del cuerpo, palma hacia arriba.",
      "Apoya el hombro y la sien derecha en el suelo.",
      "La mano izquierda queda apoyada adelante o rodea la espalda baja.",
      "Respira hacia la parte de atrás de las costillas. Cambia de lado.",
    ],
    respirar: "Lenta. El giro se profundiza en la exhalación, no empujando.",
    mejoraCon: ["manta"],
    evita: ["hombros", "cuello", "rodillas", "osteoporosis"],
    prioridad: 3,
    figura: "aguja",
  },
  {
    id: "cal-cachorro",
    fase: "calentamiento",
    nombre: "Cachorro",
    sanscrito: "Uttana Shishosana",
    familia: "cuadrupedia",
    segundos: 60,
    minimo: 45,
    maximo: 180,
    nivel: 1,
    carga: 1,
    estilos: ["yin", "hatha"],
    objetivos: ["cuello_hombros", "pecho", "postura", "flexibilidad"],
    trabaja:
      "Abre el pecho y los hombros con las caderas fijas sobre las rodillas, así el arco no se escapa a la espalda baja.",
    como: [
      "Desde cuatro apoyos, camina las manos adelante y deja las caderas sobre las rodillas.",
      "Baja el pecho y la frente hacia el suelo.",
      "Los codos quedan levantados, las axilas se abren.",
    ],
    mejoraCon: ["manta", "bloque"],
    evita: ["hombros", "rodillas"],
    masFacil: "Frente sobre un bloque o una manta doblada.",
    prioridad: 4,
    figura: "cachorro",
  },
  {
    id: "cal-gato-equilibrio",
    fase: "calentamiento",
    nombre: "Brazo y pierna opuestos",
    familia: "cuadrupedia",
    segundos: 50,
    minimo: 40,
    maximo: 80,
    porLado: true,
    nivel: 1,
    carga: 2,
    estilos: ["hatha", "iyengar"],
    objetivos: ["espalda", "fuerza", "equilibrio", "postura"],
    trabaja:
      "Activa los extensores profundos de la columna y el glúteo sin cargar la espalda: es el ejercicio de estabilidad lumbar más repetido en rehabilitación.",
    como: [
      "En cuatro apoyos, estira el brazo derecho adelante y la pierna izquierda atrás.",
      "Deja la pelvis pareja, sin abrir la cadera al techo.",
      "Sostén respirando y cambia de lado.",
    ],
    mejoraCon: ["manta"],
    evita: ["munecas", "rodillas"],
    masExigente: "Lleva el codo y la rodilla al centro y vuelve a estirar, lento.",
    prioridad: 3,
    figura: "gato_equilibrio",
  },
  {
    id: "cal-guerrero-silla",
    fase: "calentamiento",
    nombre: "Brazos y costados en la silla",
    familia: "sentada",
    segundos: 60,
    minimo: 45,
    maximo: 90,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["silla"],
    objetivos: ["postura", "cuello_hombros", "pecho", "piernas"],
    trabaja: "Alarga el costado del tronco y los intercostales, que se comprimen al estar encorvada.",
    como: [
      "Sentada al borde de la silla, pies firmes en el suelo.",
      "Sube el brazo derecho e inclínate hacia la izquierda.",
      "Mantén la nalga derecha pegada al asiento.",
      "Cambia de lado.",
    ],
    necesita: ["silla"],
    prioridad: 2,
    figura: "luna_sentada",
  },

  // ══ Saludo al sol ══════════════════════════════════════════

  {
    id: "sal-brazos-arriba",
    fase: "saludos",
    nombre: "Brazos arriba",
    sanscrito: "Urdhva Hastasana",
    familia: "de_pie",
    segundos: 12,
    minimo: 8,
    maximo: 20,
    nivel: 1,
    carga: 1,
    estilos: [],
    objetivos: [],
    trabaja: "Alarga todo el frente del cuerpo y abre las costillas antes de bajar.",
    como: ["Inhala y sube los brazos por los lados.", "Alarga desde la cintura, hombros abajo."],
    respirar: "Se entra inhalando.",
    evita: ["hombros"],
    soloEnSecuencia: true,
    prioridad: 1,
    figura: "brazos_arriba_pie",
  },
  {
    id: "sal-media-pinza",
    fase: "saludos",
    nombre: "Media pinza",
    sanscrito: "Ardha Uttanasana",
    familia: "de_pie",
    segundos: 10,
    minimo: 6,
    maximo: 16,
    nivel: 1,
    carga: 1,
    estilos: [],
    objetivos: [],
    trabaja:
      "La espalda plana a media altura. Es el paso que enseña a doblarse desde la cadera, como una bisagra, en vez de redondear la espalda.",
    como: [
      "Manos en las espinillas o en bloques, y alarga el pecho hacia adelante.",
      "La espalda queda plana, la mirada un poco adelante.",
    ],
    respirar: "Se entra inhalando.",
    evita: ["lumbar", "glaucoma"],
    soloEnSecuencia: true,
    prioridad: 1,
    figura: "media_pinza",
  },
  {
    id: "sal-chaturanga",
    fase: "saludos",
    nombre: "Chaturanga",
    sanscrito: "Chaturanga Dandasana",
    familia: "cuadrupedia",
    segundos: 10,
    minimo: 6,
    maximo: 16,
    nivel: 3,
    carga: 3,
    estilos: ["vinyasa", "ashtanga"],
    objetivos: ["fuerza"],
    trabaja:
      "Bajada controlada desde la plancha con los codos pegados al cuerpo. Es el paso donde más se lesiona el hombro en vinyasa, por dejar caer el pecho.",
    como: [
      "Desde la plancha, rueda un poco hacia adelante sobre los dedos de los pies, hasta que los hombros queden por delante de las muñecas.",
      "Baja hasta que los codos queden a noventa grados, pegados a las costillas.",
      "Hombros nunca más abajo que los codos.",
    ],
    cuidado: "Si no puedes bajar controlando, apoya las rodillas. Es la versión correcta, no la versión fácil.",
    evita: ["munecas", "hombros", "lumbar", "embarazo", "cirugia"],
    masFacil: "Rodillas al suelo antes de bajar el pecho.",
    soloEnSecuencia: true,
    prioridad: 2,
    figura: "chaturanga",
  },
  {
    id: "sal-perro-arriba",
    fase: "saludos",
    nombre: "Perro mirando hacia arriba",
    sanscrito: "Urdhva Mukha Svanasana",
    familia: "boca_abajo",
    segundos: 12,
    minimo: 8,
    maximo: 20,
    nivel: 2,
    carga: 2,
    estilos: ["vinyasa", "ashtanga"],
    objetivos: ["pecho", "postura"],
    trabaja:
      "Apertura de pecho con los muslos despegados del suelo: el peso queda en las manos y en el empeine, que es la parte de arriba del pie apoyada contra el suelo.",
    como: [
      "Empuja las manos y sube el pecho llevándolo adelante.",
      "Muslos y rodillas despegados del suelo.",
      "Hombros lejos de las orejas; la mirada al frente, no al techo.",
    ],
    cuidado: "Si la espalda baja se aprieta, quédate en la cobra.",
    evita: ["munecas", "hombros", "lumbar", "cuello", "embarazo", "cirugia"],
    masFacil: "Haz cobra: mismo movimiento, con las piernas apoyadas.",
    soloEnSecuencia: true,
    prioridad: 2,
    figura: "perro_arriba",
  },

  // ══ De pie ═════════════════════════════════════════════════
  {
    id: "pie-montana",
    fase: "de_pie",
    nombre: "Montaña",
    sanscrito: "Tadasana",
    familia: "de_pie",
    segundos: 45,
    minimo: 30,
    maximo: 70,
    nivel: 1,
    carga: 1,
    estilos: ["iyengar", "hatha"],
    objetivos: ["postura", "equilibrio", "foco"],
    trabaja:
      "Es la postura donde se aprende a apilar los huesos: pies, pelvis, costillas y cabeza en un mismo eje. Todo lo de pie se construye sobre esto.",
    como: [
      "Pies paralelos, a lo ancho de las caderas.",
      "Reparte el peso entre el dedo gordo, el meñique y el talón.",
      "Alarga desde la coronilla, hombros atrás y abajo.",
      "Costillas adentro: no empujes el pecho hacia adelante.",
    ],
    soloPrimeraVez: true,
    prioridad: 1,
    figura: "montana",
  },
  {
    id: "pie-perro",
    fase: "de_pie",
    nombre: "Perro mirando hacia abajo",
    sanscrito: "Adho Mukha Svanasana",
    familia: "cuadrupedia",
    segundos: 50,
    minimo: 35,
    maximo: 90,
    nivel: 1,
    carga: 2,
    estilos: ["vinyasa", "ashtanga", "hatha", "iyengar"],
    objetivos: ["flexibilidad", "fuerza", "cuello_hombros", "piernas", "energia"],
    trabaja:
      "Estira la parte de atrás de las piernas y abre los hombros mientras los brazos sostienen parte del peso. Es la postura de descanso del vinyasa y el eje del saludo al sol.",
    como: [
      "Desde cuatro apoyos, dobla los dedos de los pies contra el suelo, como si fueras a empujar con ellos, y sube las caderas.",
      "Dobla las rodillas todo lo que necesites: primero la espalda larga, después las piernas.",
      "Empuja el suelo con las manos y lleva las caderas atrás y arriba.",
      "Cabeza suelta entre los brazos, orejas lejos de los hombros.",
    ],
    respirar: "Cinco respiraciones largas. Si te falta el aire, baja a la postura del niño.",
    evita: ["munecas", "hombros", "glaucoma", "hipertension", "vertigo", "cirugia"],
    masFacil: "Manos en una silla o en la pared en vez del suelo: misma forma, sin la cabeza abajo.",
    prioridad: 2,
    figura: "perro_abajo",
  },
  {
    id: "pie-plancha",
    fase: "de_pie",
    nombre: "Plancha",
    sanscrito: "Phalakasana",
    familia: "cuadrupedia",
    segundos: 35,
    minimo: 20,
    maximo: 60,
    nivel: 2,
    carga: 3,
    estilos: ["vinyasa", "ashtanga"],
    objetivos: ["fuerza", "postura"],
    trabaja:
      "Sostiene todo el cuerpo en una línea: abdomen, glúteo y hombros trabajando juntos. Es fuerza de centro sin flexionar la columna.",
    como: [
      "Manos bajo los hombros, piernas atrás, cuerpo en una sola línea.",
      "Talones hacia atrás, coronilla hacia adelante.",
      "No dejes caer la cadera ni la subas: mira que el cuerpo sea una tabla.",
    ],
    cuidado: "Si la espalda baja se hunde, baja las rodillas. Sostener mal no suma.",
    evita: ["munecas", "hombros", "lumbar", "embarazo", "cirugia"],
    masFacil: "Rodillas en el suelo, o manos en una silla.",
    prepararCon: ["cal-gato-equilibrio"],
    prioridad: 4,
    figura: "plancha",
  },
  {
    id: "pie-silla",
    fase: "de_pie",
    nombre: "La silla",
    sanscrito: "Utkatasana",
    familia: "de_pie",
    segundos: 45,
    minimo: 30,
    maximo: 70,
    nivel: 2,
    carga: 3,
    estilos: ["vinyasa", "ashtanga", "hatha"],
    objetivos: ["fuerza", "piernas", "energia"],
    trabaja: "Trabaja cuádriceps y glúteo sosteniendo el propio peso, con los brazos arriba cargando también los hombros.",
    como: [
      "De pie, pies juntos o a lo ancho de las caderas.",
      "Dobla las rodillas como si te sentaras en una silla que no está.",
      "Lleva el peso a los talones: si te miras los pies, tienes que poder verte los dedos.",
      "Sube los brazos, mira al frente.",
    ],
    respirar: "Respira parejo, aunque quemen las piernas.",
    evita: ["rodillas", "hombros", "hipertension"],
    masFacil: "Baja menos y deja las manos en el pecho.",
    prioridad: 3,
    figura: "silla_postura",
  },
  {
    id: "pie-guerrero1",
    fase: "de_pie",
    nombre: "Guerrero I",
    sanscrito: "Virabhadrasana I",
    familia: "de_pie",
    segundos: 60,
    minimo: 40,
    maximo: 90,
    porLado: true,
    nivel: 2,
    carga: 2,
    estilos: ["hatha", "vinyasa", "iyengar"],
    objetivos: ["fuerza", "pecho", "piernas", "postura"],
    trabaja:
      "Abre el psoas y el flexor de la cadera de la pierna de atrás — el músculo que se acorta con las horas sentada — mientras la de adelante trabaja fuerza.",
    como: [
      "Un pie adelante, el otro un paso atrás con el talón apoyado en diagonal.",
      "Las caderas miran al frente, lo más parejas que puedas.",
      "Dobla la rodilla de adelante hacia el tobillo, no más allá.",
      "Sube los brazos y alarga desde la cintura.",
    ],
    cuidado: "La rodilla de adelante no pasa la línea del tobillo ni se cae hacia adentro.",
    evita: ["rodillas", "hombros"],
    masFacil: "Manos en las caderas y separa más los pies, como sobre rieles de tren.",
    prioridad: 2,
    figura: "guerrero1",
  },
  {
    id: "pie-guerrero2",
    fase: "de_pie",
    nombre: "Guerrero II",
    sanscrito: "Virabhadrasana II",
    familia: "de_pie",
    segundos: 60,
    minimo: 40,
    maximo: 90,
    porLado: true,
    nivel: 1,
    carga: 2,
    estilos: ["hatha", "vinyasa", "iyengar", "ashtanga"],
    objetivos: ["fuerza", "caderas", "piernas", "foco"],
    trabaja: "Abre la cadera al plano lateral y trabaja el glúteo medio, que estabiliza la pelvis al caminar.",
    como: [
      "Pies separados un paso largo, el de adelante mirando al frente, el de atrás girado.",
      "Dobla la rodilla de adelante sobre el tobillo.",
      "Brazos a la altura de los hombros, mira sobre la mano de adelante.",
      "El tronco queda al centro, no se va hacia adelante.",
    ],
    evita: ["rodillas", "hombros"],
    masFacil: "Dobla menos la rodilla y baja los brazos cuando cansen.",
    prioridad: 2,
    figura: "guerrero2",
  },
  {
    id: "pie-angulo-lateral",
    fase: "de_pie",
    nombre: "Ángulo lateral",
    sanscrito: "Utthita Parsvakonasana",
    familia: "de_pie",
    segundos: 55,
    minimo: 40,
    maximo: 90,
    porLado: true,
    nivel: 2,
    carga: 2,
    estilos: ["iyengar", "vinyasa", "ashtanga"],
    objetivos: ["caderas", "flexibilidad", "piernas", "pecho"],
    trabaja: "Alarga todo el costado del cuerpo, desde el borde del pie de atrás hasta la punta de los dedos.",
    como: [
      "Desde guerrero II, apoya el antebrazo sobre el muslo de adelante o la mano en un bloque.",
      "Estira el otro brazo por encima de la oreja.",
      "Gira el pecho hacia el techo, no hacia el suelo.",
    ],
    mejoraCon: ["bloque"],
    evita: ["rodillas", "hombros", "cuello"],
    prioridad: 4,
    figura: "angulo_lateral",
  },
  {
    id: "pie-triangulo",
    fase: "de_pie",
    nombre: "Triángulo",
    sanscrito: "Trikonasana",
    familia: "de_pie",
    segundos: 55,
    minimo: 40,
    maximo: 90,
    porLado: true,
    nivel: 2,
    carga: 2,
    estilos: ["iyengar", "hatha", "ashtanga"],
    objetivos: ["flexibilidad", "caderas", "postura", "pecho"],
    trabaja:
      "Estira isquiotibiales y el costado del tronco a la vez. Es la postura donde más se nota si estás doblando la columna en vez de la cadera.",
    como: [
      "Pies separados un paso largo, el de adelante hacia el frente.",
      "Alarga el tronco sobre la pierna de adelante y baja la mano a la espinilla o a un bloque.",
      "La otra mano sube al techo; el pecho se abre al costado.",
      "Las dos piernas quedan rectas, sin bloquear la rodilla.",
    ],
    cuidado: "No apoyes la mano en la rodilla: la empuja hacia atrás.",
    mejoraCon: ["bloque"],
    evita: ["lumbar", "cuello", "hipermovilidad"],
    masFacil: "Mano en un bloque alto o en la espinilla, y mira al frente en vez de al techo.",
    prepararCon: ["pie-guerrero2"],
    prioridad: 3,
    figura: "triangulo",
  },
  {
    id: "pie-piernas-abiertas",
    fase: "de_pie",
    nombre: "Pinza con piernas abiertas",
    sanscrito: "Prasarita Padottanasana",
    familia: "de_pie",
    segundos: 60,
    minimo: 45,
    maximo: 120,
    nivel: 2,
    carga: 2,
    estilos: ["ashtanga", "iyengar", "hatha"],
    objetivos: ["flexibilidad", "caderas", "calma", "piernas"],
    trabaja: "Estira los aductores y la parte de atrás de las piernas con la cabeza colgando, lo que baja el ritmo.",
    como: [
      "Pies bien separados y paralelos.",
      "Manos en las caderas, alarga la espalda y baja desde la cadera.",
      "Apoya las manos en el suelo o en un bloque, cabeza pesada.",
      "Para salir, sube con la espalda larga y las rodillas blandas.",
    ],
    mejoraCon: ["bloque"],
    evita: ["lumbar", "hipertension", "glaucoma", "vertigo", "osteoporosis"],
    prioridad: 4,
    figura: "piernas_abiertas_pie",
  },
  {
    id: "pie-estocada-baja",
    fase: "de_pie",
    nombre: "Estocada baja",
    sanscrito: "Anjaneyasana",
    familia: "de_pie",
    segundos: 60,
    minimo: 45,
    maximo: 150,
    porLado: true,
    nivel: 1,
    carga: 2,
    estilos: ["hatha", "vinyasa", "yin"],
    objetivos: ["caderas", "espalda", "flexibilidad", "postura"],
    trabaja:
      "El estiramiento más directo del psoas y el recto femoral. Si pasas el día sentada, esta es la postura que más vas a sentir.",
    como: [
      "Un pie adelante entre las manos, la rodilla de atrás en el suelo.",
      "Hunde la cadera hacia adelante y hacia abajo.",
      "Lleva el hueso de la cola hacia abajo, como metiendo la pelvis: el estiramiento aparece justo cuando dejas de arquear la espalda baja.",
      "Sube los brazos si quieres más.",
    ],
    mejoraCon: ["manta", "bloque"],
    evita: ["rodillas"],
    masFacil: "Manta doblada bajo la rodilla de atrás y manos en bloques.",
    prioridad: 2,
    figura: "estocada_baja",
  },
  {
    id: "pie-guirnalda",
    fase: "de_pie",
    nombre: "Guirnalda",
    sanscrito: "Malasana",
    familia: "de_pie",
    segundos: 60,
    minimo: 40,
    maximo: 180,
    nivel: 2,
    carga: 2,
    estilos: ["hatha", "yin"],
    objetivos: ["caderas", "espalda", "digestion", "menstrual", "embarazo"],
    trabaja: "Cuclillas profundas: abre la cadera, el suelo pélvico y la parte baja de la espalda.",
    como: [
      "Pies un poco más anchos que las caderas, puntas hacia afuera.",
      "Baja en cuclillas, talones al suelo si llegan.",
      "Codos por dentro de las rodillas, manos en el pecho.",
      "Alarga la espalda hacia arriba.",
    ],
    mejoraCon: ["bloque", "manta"],
    evita: ["rodillas"],
    masFacil: "Siéntate sobre un bloque o enrolla una manta bajo los talones.",
    prioridad: 4,
    figura: "guirnalda",
  },
  {
    id: "pie-pinza",
    fase: "de_pie",
    nombre: "Pinza de pie",
    sanscrito: "Uttanasana",
    familia: "de_pie",
    segundos: 55,
    minimo: 40,
    maximo: 120,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "vinyasa", "ashtanga"],
    objetivos: ["calma", "flexibilidad", "espalda", "piernas"],
    trabaja: "Estira toda la cadena de atrás y deja la cabeza colgando, lo que suele bajar el pulso.",
    como: [
      "De pie, dobla las rodillas todo lo que necesites.",
      "Deja caer el tronco sobre los muslos, panza cerca de los muslos.",
      "Suelta la cabeza y los brazos.",
      "Sube lento, desenrollando la columna.",
    ],
    cuidado: "Las rodillas dobladas no son trampa: la columna importa más que la pierna recta.",
    evita: ["lumbar", "hipertension", "glaucoma", "vertigo", "osteoporosis"],
    prioridad: 3,
    figura: "pinza_de_pie",
  },
  {
    id: "pie-pared-hombros",
    fase: "de_pie",
    nombre: "Perro en la pared",
    familia: "de_pie",
    segundos: 60,
    minimo: 45,
    maximo: 90,
    nivel: 1,
    carga: 1,
    estilos: ["iyengar", "silla"],
    objetivos: ["cuello_hombros", "postura", "espalda", "pecho"],
    trabaja:
      "La apertura de hombros del perro mirando hacia abajo, sin poner peso en las muñecas ni la cabeza bajo el corazón.",
    como: [
      "Manos en la pared a la altura de las caderas.",
      "Camina los pies atrás hasta formar una L con el cuerpo.",
      "Empuja la pared y alarga desde las axilas hasta la cola.",
    ],
    necesita: ["pared"],
    prioridad: 3,
    figura: "hombros_pared",
  },
  {
    id: "pie-silla-torsion",
    fase: "de_pie",
    nombre: "Torsión sentada en la silla",
    familia: "sentada",
    segundos: 50,
    minimo: 40,
    maximo: 80,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["silla"],
    objetivos: ["espalda", "digestion", "postura"],
    trabaja: "Gira la columna dorsal usando el respaldo como palanca suave.",
    como: [
      "Sentada de lado en la silla, pies firmes en el suelo.",
      "Toma el respaldo con las dos manos y gira desde las costillas.",
      "Alarga primero hacia arriba, después gira. Cambia de lado.",
    ],
    necesita: ["silla"],
    evita: ["embarazo", "osteoporosis"],
    prioridad: 3,
    figura: "sentada_torsion_silla",
  },

  // ══ Equilibrio ═════════════════════════════════════════════
  {
    id: "eq-arbol",
    fase: "equilibrio",
    nombre: "El árbol",
    sanscrito: "Vrksasana",
    familia: "de_pie",
    segundos: 45,
    minimo: 30,
    maximo: 70,
    porLado: true,
    nivel: 1,
    carga: 2,
    estilos: ["hatha", "iyengar"],
    objetivos: ["equilibrio", "foco", "piernas"],
    trabaja:
      "Trabaja el tobillo y el glúteo medio del lado que sostiene, y obliga a la mirada y la respiración a quedarse quietas.",
    como: [
      "De pie, lleva el peso a la pierna derecha.",
      "Apoya la planta del pie izquierdo en el tobillo, la pantorrilla o el muslo. Nunca en la rodilla.",
      "Junta las manos en el pecho y fija la mirada en un punto quieto.",
      "Cambia de lado.",
    ],
    cuidado: "El pie nunca va apoyado contra la rodilla: la empuja hacia el lado.",
    mejoraCon: ["pared"],
    masFacil: "Apoya una mano en la pared, o deja los dedos del pie en el suelo como pata de kickstand.",
    prioridad: 2,
    figura: "arbol",
  },
  {
    id: "eq-guerrero3",
    fase: "equilibrio",
    nombre: "Guerrero III",
    sanscrito: "Virabhadrasana III",
    familia: "de_pie",
    segundos: 35,
    minimo: 25,
    maximo: 55,
    porLado: true,
    nivel: 3,
    carga: 3,
    estilos: ["vinyasa", "iyengar"],
    objetivos: ["equilibrio", "fuerza", "postura"],
    trabaja: "Toda la cadena de atrás sosteniendo el cuerpo en horizontal sobre una pierna.",
    como: [
      "Desde una estocada corta, lleva el peso al pie de adelante.",
      "Estira la otra pierna atrás hasta la altura de la cadera.",
      "Tronco y pierna forman una sola línea; las caderas quedan parejas.",
      "Brazos atrás, a los lados o adelante, según lo que aguantes.",
    ],
    mejoraCon: ["pared", "bloque"],
    evita: ["lumbar", "vertigo", "embarazo"],
    masFacil: "Manos en la pared a la altura de las caderas, o en dos bloques.",
    prepararCon: ["pie-guerrero1"],
    prioridad: 5,
    figura: "guerrero3",
  },
  {
    id: "eq-equilibrio-silla",
    fase: "equilibrio",
    nombre: "Equilibrio con apoyo",
    familia: "de_pie",
    segundos: 40,
    minimo: 30,
    maximo: 60,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["silla", "somatico"],
    objetivos: ["equilibrio", "piernas", "foco"],
    trabaja:
      "Entrena el tobillo y el reflejo de estabilización con la seguridad de una mano apoyada. Es la versión que se usa en los programas de prevención de caídas.",
    como: [
      "De pie detrás de una silla, una mano en el respaldo.",
      "Levanta un pie unos centímetros y sostén.",
      "Si va bien, suelta la mano un momento y vuelve a apoyarla.",
      "Cambia de pie.",
    ],
    necesita: ["silla"],
    prioridad: 2,
    figura: "equilibrio_silla",
    fuente: "Formato de los programas de equilibrio para prevención de caídas",
  },

  // ══ Suelo y caderas ════════════════════════════════════════
  {
    id: "sue-mariposa",
    fase: "suelo",
    nombre: "Mariposa",
    sanscrito: "Baddha Konasana",
    familia: "sentada",
    segundos: 90,
    minimo: 50,
    maximo: 300,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "yin", "iyengar"],
    objetivos: ["caderas", "menstrual", "embarazo", "calma", "flexibilidad"],
    trabaja:
      "Abre los aductores y rota la cadera hacia afuera. Sentada sobre una manta la pelvis se endereza y el estiramiento deja de tirar de la espalda baja.",
    como: [
      "Sentada, junta las plantas de los pies y deja caer las rodillas a los lados.",
      "Sube sobre el borde de una manta doblada si la espalda se redondea.",
      "Toma los tobillos y alarga la coronilla hacia arriba.",
      "Si quieres más, baja el pecho hacia adelante desde la cadera, no desde la cintura.",
    ],
    cuidado: "No empujes las rodillas hacia abajo con las manos.",
    mejoraCon: ["manta", "bloque", "bolster"],
    evita: ["rodillas"],
    masFacil: "Aleja los pies del cuerpo y pon un bloque bajo cada rodilla.",
    prioridad: 2,
    figura: "mariposa",
  },
  {
    id: "sue-paloma",
    fase: "suelo",
    nombre: "Paloma",
    sanscrito: "Eka Pada Rajakapotasana",
    familia: "sentada",
    segundos: 90,
    minimo: 60,
    maximo: 300,
    porLado: true,
    nivel: 2,
    carga: 2,
    estilos: ["vinyasa", "yin", "hatha"],
    objetivos: ["caderas", "espalda", "flexibilidad"],
    trabaja:
      "Estira el glúteo y los rotadores profundos de la cadera, incluido el piramidal, que es el que aprieta el nervio ciático cuando está contracturado.",
    como: [
      "Desde cuatro apoyos, lleva la rodilla derecha detrás de la mano derecha.",
      "La espinilla queda en diagonal; la pierna izquierda estirada atrás.",
      "Pon una manta bajo la nalga derecha para que la cadera quede pareja.",
      "Baja el pecho sobre la pierna o quédate arriba con las manos apoyadas.",
    ],
    cuidado: "Si aparece dolor en la rodilla de adelante, sal: el giro se está yendo a la rodilla en vez de a la cadera.",
    mejoraCon: ["manta", "bolster", "bloque"],
    evita: ["rodillas", "ciatica"],
    masFacil: "Hazla acostada de espaldas (figura de cuatro): mismo músculo, cero peso en la rodilla.",
    prepararCon: ["pie-estocada-baja"],
    prioridad: 4,
    figura: "paloma",
  },
  {
    id: "sue-cuatro",
    fase: "suelo",
    nombre: "Figura de cuatro",
    sanscrito: "Supta Kapotasana",
    familia: "supina",
    segundos: 75,
    minimo: 50,
    maximo: 180,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "somatico", "restaurativo"],
    objetivos: ["caderas", "espalda", "piernas"],
    trabaja:
      "El mismo estiramiento de glúteo que la paloma, pero de espaldas: la rodilla no carga nada y tú controlas cuánto entra.",
    como: [
      "Acostada boca arriba, rodillas dobladas y pies en el suelo.",
      "Cruza el tobillo derecho sobre el muslo izquierdo, formando un cuatro.",
      "Toma la parte de atrás del muslo izquierdo y acércalo al pecho.",
      "Empuja suave la rodilla derecha con el codo. Cambia de lado.",
    ],
    mejoraCon: ["cinturon"],
    evita: ["rodillas", "embarazo"],
    prioridad: 2,
    figura: "cuatro_supina",
  },
  {
    id: "sue-pierna-cinturon",
    fase: "suelo",
    nombre: "Pierna al techo con cinturón",
    sanscrito: "Supta Padangusthasana",
    familia: "supina",
    segundos: 75,
    minimo: 50,
    maximo: 150,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["iyengar", "hatha"],
    objetivos: ["flexibilidad", "piernas", "espalda"],
    trabaja:
      "Estira los isquiotibiales con la espalda apoyada en el suelo, que es la forma más segura de hacerlo si la lumbar molesta.",
    como: [
      "Acostada, pasa un cinturón por la planta del pie derecho.",
      "Estira la pierna hacia el techo hasta donde llegue, sin bloquear la rodilla.",
      "La otra pierna queda doblada con el pie en el suelo, o estirada.",
      "Hombros pesados en el suelo. Cambia de lado.",
    ],
    necesita: ["cinturon"],
    evita: ["embarazo"],
    masFacil: "Dobla la rodilla de la pierna que sube: el estiramiento sigue estando.",
    prioridad: 3,
    figura: "supina_pierna_estirada",
  },
  {
    id: "sue-cabeza-rodilla",
    fase: "suelo",
    nombre: "Cabeza a la rodilla",
    sanscrito: "Janu Sirsasana",
    familia: "sentada",
    segundos: 80,
    minimo: 50,
    maximo: 240,
    porLado: true,
    nivel: 2,
    carga: 1,
    estilos: ["hatha", "ashtanga", "yin"],
    objetivos: ["flexibilidad", "calma", "digestion", "piernas"],
    trabaja: "Estira una pierna por vez y el costado del tronco, con la cadera de la pierna doblada abierta.",
    como: [
      "Sentada, estira la pierna derecha y apoya la planta del pie izquierdo en el muslo derecho.",
      "Alarga la columna y baja sobre la pierna desde la cadera.",
      "Usa un cinturón alrededor del pie si no llegas.",
      "Cambia de lado.",
    ],
    mejoraCon: ["cinturon", "manta", "bolster"],
    evita: ["lumbar", "ciatica", "osteoporosis", "rodillas"],
    prioridad: 4,
    figura: "cabeza_rodilla",
  },
  {
    id: "sue-pinza-sentada",
    fase: "suelo",
    nombre: "Pinza sentada",
    sanscrito: "Paschimottanasana",
    familia: "sentada",
    segundos: 90,
    minimo: 60,
    maximo: 300,
    nivel: 2,
    carga: 1,
    estilos: ["hatha", "yin", "ashtanga"],
    objetivos: ["calma", "flexibilidad", "dormir", "piernas"],
    trabaja:
      "Estiramiento largo de toda la cadena de atrás. En yin se sostiene de tres a cinco minutos, con las rodillas dobladas y sin buscar forma.",
    como: [
      "Sentada con las piernas estiradas, sube sobre una manta doblada.",
      "Dobla un poco las rodillas y baja el tronco sobre las piernas.",
      "Apoya el pecho en un cojín si lo tienes; la idea es soltar, no llegar.",
      "Deja caer la cabeza y quédate.",
    ],
    cuidado: "Si la espalda se redondea en la zona lumbar y duele, dobla más las rodillas o sal.",
    mejoraCon: ["manta", "bolster", "cinturon"],
    evita: ["lumbar", "ciatica", "osteoporosis", "embarazo"],
    prepararCon: ["sue-cabeza-rodilla"],
    prioridad: 4,
    figura: "pinza_sentada",
  },
  {
    id: "sue-nino",
    fase: "suelo",
    nombre: "Postura del niño",
    sanscrito: "Balasana",
    familia: "cuadrupedia",
    segundos: 75,
    minimo: 45,
    maximo: 240,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "restaurativo", "yin"],
    objetivos: ["calma", "espalda", "dormir", "menstrual"],
    trabaja:
      "Redondea suave la espalda baja y pone la frente en el suelo. Es la postura de descanso a la que se puede volver en cualquier momento de la práctica.",
    como: [
      "De rodillas, junta los dedos gordos de los pies y separa las rodillas.",
      "Siéntate sobre los talones y baja la frente al suelo.",
      "Brazos estirados adelante o sueltos al lado del cuerpo.",
      "Respira hacia la espalda: siente cómo se abren las costillas de atrás.",
    ],
    mejoraCon: ["manta", "bolster", "bloque"],
    evita: ["rodillas"],
    masFacil: "Manta gruesa entre las nalgas y los talones, y un cojín bajo el pecho.",
    prioridad: 1,
    figura: "nino",
  },
  {
    id: "sue-zapatero-apoyado",
    fase: "suelo",
    nombre: "Mariposa acostada",
    sanscrito: "Supta Baddha Konasana",
    familia: "supina",
    segundos: 180,
    minimo: 90,
    maximo: 420,
    nivel: 1,
    carga: 1,
    estilos: ["restaurativo", "yin", "iyengar", "nidra"],
    objetivos: ["calma", "dormir", "menstrual", "caderas", "pecho"],
    trabaja:
      "Abre pecho y caderas sin que el cuerpo sostenga nada: con el cojín debajo de la columna, los músculos se pueden apagar del todo.",
    como: [
      "Pon un cojín largo o dos almohadas a lo largo, detrás de ti.",
      "Siéntate delante, junta las plantas de los pies y acuéstate sobre el apoyo.",
      "Un bloque o cojín bajo cada rodilla: si las piernas cuelgan, la cadera no suelta.",
      "Brazos abiertos, palmas arriba. Quédate.",
    ],
    necesita: ["bolster"],
    mejoraCon: ["manta", "bloque"],
    evita: ["rodillas"],
    prioridad: 2,
    figura: "zapatero_apoyado",
  },
  {
    id: "sue-bebe-feliz",
    fase: "suelo",
    nombre: "Bebé feliz",
    sanscrito: "Ananda Balasana",
    familia: "supina",
    segundos: 60,
    minimo: 40,
    maximo: 150,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "yin"],
    objetivos: ["caderas", "espalda", "menstrual", "calma"],
    trabaja: "Abre la cadera y suelta la espalda baja con el sacro apoyado y pesado en el suelo.",
    como: [
      "Acostada, dobla las rodillas hacia las axilas.",
      "Toma los bordes externos de los pies, o las pantorrillas si no llegas.",
      "Tobillos sobre las rodillas, espinillas verticales.",
      "Mécete un poco de lado a lado.",
    ],
    mejoraCon: ["cinturon"],
    evita: ["embarazo"],
    prioridad: 4,
    figura: "bebe_feliz",
  },
  {
    id: "sue-barco",
    fase: "suelo",
    nombre: "El barco",
    sanscrito: "Navasana",
    familia: "sentada",
    segundos: 35,
    minimo: 25,
    maximo: 60,
    nivel: 2,
    carga: 3,
    estilos: ["ashtanga", "vinyasa"],
    objetivos: ["fuerza", "foco", "postura"],
    trabaja: "Carga el psoas y toda la pared abdominal sosteniendo las piernas fuera del suelo.",
    como: [
      "Sentada, inclínate atrás y levanta los pies con las rodillas dobladas.",
      "Espalda larga, pecho abierto: si se redondea, bajas las piernas.",
      "Brazos paralelos al suelo.",
    ],
    evita: ["lumbar", "embarazo", "cirugia"],
    masFacil:
      "Tómate la parte de atrás de los muslos con las manos y deja las puntas de los pies apoyadas en el suelo.",
    masExigente: "Estira las piernas hasta formar una V.",
    prioridad: 5,
    figura: "barco",
  },
  {
    id: "sue-estocada-yin",
    fase: "suelo",
    nombre: "Dragón",
    sanscrito: "Estocada yin",
    familia: "de_pie",
    segundos: 150,
    minimo: 90,
    maximo: 300,
    porLado: true,
    nivel: 2,
    carga: 2,
    estilos: ["yin"],
    objetivos: ["caderas", "flexibilidad", "espalda"],
    trabaja:
      "La estocada sostenida varios minutos. En yin la idea es quedarse quieta en un estiramiento moderado y dejar que el tejido ceda con el tiempo, no forzar.",
    como: [
      "Estocada con la rodilla de atrás en el suelo, sobre una manta.",
      "Baja los antebrazos a bloques o al suelo, por dentro del pie de adelante.",
      "Quédate de dos a cinco minutos. Va a costar: eso es yin.",
      "Sal despacio y muévete un poco antes de cambiar de lado.",
    ],
    cuidado: "Dolor agudo o eléctrico, se sale. La incomodidad sorda se puede sostener.",
    mejoraCon: ["manta", "bloque"],
    evita: ["rodillas", "hipermovilidad"],
    prepararCon: ["cal-cadera-circulos"],
    prioridad: 5,
    figura: "estocada_baja",
  },

  // ══ Abrir el pecho ═════════════════════════════════════════
  {
    id: "ext-esfinge",
    fase: "extensiones",
    nombre: "Esfinge",
    sanscrito: "Salamba Bhujangasana",
    familia: "boca_abajo",
    segundos: 75,
    minimo: 45,
    maximo: 240,
    nivel: 1,
    carga: 1,
    estilos: ["yin", "hatha", "iyengar"],
    objetivos: ["espalda", "postura", "pecho"],
    trabaja:
      "Extensión suave y sostenida de la columna lumbar con los antebrazos apoyados. Es la más accesible de las posturas hacia atrás.",
    como: [
      "Boca abajo, codos bajo los hombros y antebrazos paralelos.",
      "Empuja los antebrazos contra el suelo y alarga el pecho hacia adelante.",
      "Piernas y glúteos blandos.",
      "Si molesta la espalda baja, aleja los codos hacia adelante.",
    ],
    evita: ["embarazo", "lumbar", "cirugia"],
    prioridad: 2,
    figura: "esfinge",
  },
  {
    id: "ext-cobra",
    fase: "extensiones",
    nombre: "Cobra",
    sanscrito: "Bhujangasana",
    familia: "boca_abajo",
    segundos: 50,
    minimo: 35,
    maximo: 80,
    nivel: 2,
    carga: 2,
    estilos: ["hatha", "vinyasa", "ashtanga"],
    objetivos: ["espalda", "pecho", "postura", "energia"],
    trabaja:
      "Extensión activa de la columna: la levantan los músculos de la espalda, no los brazos. Por eso se sube poco y se sostiene.",
    como: [
      "Boca abajo, manos bajo los hombros, codos pegados al cuerpo.",
      "Sube el pecho usando la espalda; deja las manos casi sin peso.",
      "Hombros lejos de las orejas, mirada al frente.",
      "Baja al exhalar.",
    ],
    cuidado: "Si aparece pinchazo en la espalda baja, bajas. Es señal de que estás cerrando la lumbar.",
    evita: ["embarazo", "lumbar", "munecas", "cirugia"],
    prioridad: 3,
    figura: "cobra",
  },
  {
    id: "ext-langosta",
    fase: "extensiones",
    nombre: "Langosta",
    sanscrito: "Salabhasana",
    familia: "boca_abajo",
    segundos: 40,
    minimo: 30,
    maximo: 60,
    nivel: 2,
    carga: 3,
    estilos: ["hatha", "ashtanga"],
    objetivos: ["postura", "fuerza", "espalda", "pecho"],
    trabaja:
      "Fortalece los extensores de la espalda y los músculos entre las escápulas, que son justamente los que se debilitan al estar encorvada.",
    como: [
      "Boca abajo, brazos a los lados del cuerpo, palmas hacia abajo.",
      "Levanta pecho, brazos y piernas del suelo al mismo tiempo.",
      "Mira al suelo para no comprimir la nuca.",
      "Baja y descansa una respiración antes de repetir.",
    ],
    evita: ["embarazo", "lumbar", "cirugia"],
    masFacil: "Sube solo el pecho, o solo las piernas, de a uno.",
    prepararCon: ["ext-esfinge"],
    prioridad: 4,
    figura: "langosta",
    formas: [
      { figura: "boca_abajo", texto: "Empieza boca abajo, brazos a los lados" },
      { figura: "langosta", texto: "Levanta pecho, brazos y piernas" },
    ],
  },
  {
    id: "ext-puente",
    fase: "extensiones",
    nombre: "Puente",
    sanscrito: "Setu Bandhasana",
    familia: "supina",
    segundos: 55,
    minimo: 40,
    maximo: 90,
    nivel: 1,
    carga: 2,
    estilos: ["hatha", "vinyasa", "iyengar"],
    objetivos: ["espalda", "pecho", "fuerza", "postura", "piernas"],
    trabaja:
      "Fortalece el glúteo y la parte de atrás del muslo, y abre la cadera adelante. Es la contrapostura natural de estar sentada.",
    como: [
      "Acostada, rodillas dobladas, pies a lo ancho de las caderas, cerca de las nalgas.",
      "Empuja los pies y sube la pelvis, vértebra por vértebra.",
      "Rodillas paralelas: no dejes que se abran.",
      "Baja lento, desenrollando la columna.",
    ],
    evita: ["cuello", "embarazo"],
    masExigente: "Entrelaza las manos bajo la espalda y rueda sobre los hombros.",
    prioridad: 2,
    figura: "puente",
    formas: [
      { figura: "supina_rodillas", texto: "Empieza así: pies cerca de las nalgas" },
      { figura: "puente", texto: "Empuja los pies y sube la cadera" },
    ],
  },
  {
    id: "ext-puente-apoyado",
    fase: "extensiones",
    nombre: "Puente apoyado",
    sanscrito: "Setu Bandha con bloque",
    familia: "supina",
    segundos: 180,
    minimo: 90,
    maximo: 420,
    nivel: 1,
    carga: 1,
    estilos: ["restaurativo", "iyengar", "yin"],
    objetivos: ["calma", "dormir", "espalda", "piernas", "pecho"],
    trabaja:
      "La misma apertura del puente pero sin esfuerzo: el bloque sostiene el sacro y el cuerpo se puede apagar. Es una de las posturas base del restaurativo.",
    como: [
      "Sube la pelvis y desliza un bloque en su altura más baja bajo el sacro, el hueso plano del final de la columna.",
      "El bloque va bajo el hueso plano, no bajo la cintura.",
      "Estira las piernas si te resulta cómodo, o déjalas dobladas.",
      "Brazos abiertos. Quédate varios minutos.",
    ],
    necesita: ["bloque"],
    evita: ["cuello", "embarazo"],
    masFacil: "Si el bloque incomoda, usa un cojín firme o una manta enrollada.",
    prioridad: 3,
    figura: "puente_apoyado",
  },
  {
    id: "ext-camello",
    fase: "extensiones",
    nombre: "Camello",
    sanscrito: "Ustrasana",
    familia: "cuadrupedia",
    segundos: 40,
    minimo: 30,
    maximo: 60,
    nivel: 3,
    carga: 3,
    estilos: ["hatha", "vinyasa"],
    objetivos: ["pecho", "postura", "energia"],
    trabaja: "Extensión grande de toda la parte de adelante del cuerpo: muslos, ingles, abdomen y pecho.",
    como: [
      "De rodillas, a lo ancho de las caderas, manos en la espalda baja.",
      "Empuja las caderas hacia adelante y abre el pecho hacia arriba.",
      "Solo si el pecho está abierto, lleva las manos a los talones.",
      "La cabeza va al final; si el cuello molesta, déjala en el eje.",
    ],
    cuidado: "No dejes caer la cabeza atrás si tienes cualquier historia de cuello. Sal siempre subiendo el pecho primero.",
    mejoraCon: ["bloque", "manta"],
    evita: ["cuello", "lumbar", "rodillas", "hipertension", "embarazo", "cirugia"],
    masFacil: "Manos en la cintura y sube solo el pecho, sin tocar los talones.",
    prepararCon: ["ext-puente"],
    prioridad: 5,
    figura: "camello",
  },
  {
    id: "ext-brazos-espalda",
    fase: "extensiones",
    nombre: "Brazos a la espalda",
    sanscrito: "Brazos de Gomukhasana",
    familia: "sentada",
    segundos: 60,
    minimo: 45,
    maximo: 90,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["iyengar", "silla", "hatha"],
    objetivos: ["cuello_hombros", "pecho", "postura"],
    trabaja: "Rota el hombro hacia afuera por arriba y hacia adentro por abajo: los dos rangos que se pierden primero.",
    como: [
      "Sube el brazo derecho y dobla el codo llevando la mano entre los omóplatos.",
      "Baja el brazo izquierdo y sube la mano por la espalda.",
      "Engancha los dedos, o usa un cinturón entre las manos.",
      "Pecho abierto, costillas adentro. Cambia de lado.",
    ],
    mejoraCon: ["cinturon"],
    evita: ["hombros"],
    prioridad: 3,
    figura: "brazos_espalda",
  },

  // ══ Torsiones ══════════════════════════════════════════════
  {
    id: "tor-sentada",
    fase: "torsiones",
    nombre: "Torsión sentada",
    sanscrito: "Ardha Matsyendrasana",
    familia: "sentada",
    segundos: 60,
    minimo: 40,
    maximo: 120,
    porLado: true,
    nivel: 2,
    carga: 1,
    estilos: ["hatha", "ashtanga", "iyengar"],
    objetivos: ["espalda", "digestion", "postura"],
    trabaja: "Rota la columna con la pelvis fija, que es lo que hace que el giro llegue a las dorsales y no solo a la cintura.",
    como: [
      "Sentada, cruza el pie derecho por fuera de la rodilla izquierda.",
      "Alarga la columna hacia arriba antes de girar.",
      "Gira hacia la derecha; la mano izquierda hace de palanca en la rodilla.",
      "Mira sobre el hombro solo si el cuello lo permite. Cambia de lado.",
    ],
    cuidado: "No uses el brazo para forzar el giro. La torsión viene del tronco.",
    mejoraCon: ["manta"],
    evita: ["embarazo", "osteoporosis", "lumbar"],
    prioridad: 3,
    figura: "torsion_sentada",
  },
  {
    id: "tor-supina",
    fase: "torsiones",
    nombre: "Torsión acostada",
    sanscrito: "Supta Matsyendrasana",
    familia: "supina",
    segundos: 90,
    minimo: 60,
    maximo: 240,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "yin", "restaurativo"],
    objetivos: ["espalda", "calma", "dormir", "digestion"],
    trabaja:
      "La torsión más suave: el suelo sostiene todo el peso, así que la columna gira sin tener que estabilizarse.",
    como: [
      "Acostada, lleva las rodillas al pecho.",
      "Déjalas caer hacia la derecha y estira el brazo izquierdo al lado.",
      "Gira la cara hacia el lado contrario, si el cuello está cómodo.",
      "Pon un cojín entre las rodillas si la espalda tira. Cambia de lado.",
    ],
    mejoraCon: ["bolster", "manta"],
    evita: ["embarazo", "osteoporosis"],
    prioridad: 2,
    figura: "torsion_supina",
  },

  // ══ Piernas arriba ═════════════════════════════════════════
  {
    id: "inv-piernas-pared",
    fase: "invertidas",
    nombre: "Piernas en la pared",
    sanscrito: "Viparita Karani",
    familia: "invertida",
    segundos: 240,
    minimo: 120,
    maximo: 600,
    nivel: 1,
    carga: 1,
    estilos: ["restaurativo", "iyengar", "yin", "nidra"],
    objetivos: ["piernas", "calma", "dormir", "menstrual"],
    trabaja:
      "Cambia de sentido el retorno venoso y linfático de las piernas, que es lo que alivia la pesadez después de horas de pie. La cabeza queda a la altura del corazón, así que no es una inversión de las que suben la presión en la cabeza.",
    como: [
      "Siéntate de lado pegada a la pared y gira para subir las piernas.",
      "Las nalgas quedan cerca de la pared, o a un palmo si tiras de isquios.",
      "Manta doblada bajo la pelvis si quieres más apoyo.",
      "Brazos abiertos, ojos cerrados. De tres a diez minutos.",
    ],
    necesita: ["pared"],
    mejoraCon: ["manta", "bolster"],
    evita: ["glaucoma", "embarazo"],
    masFacil: "Sube las piernas a una silla en vez de la pared, pantorrillas apoyadas en el asiento.",
    prioridad: 2,
    figura: "piernas_pared",
  },
  {
    id: "inv-vela",
    fase: "invertidas",
    nombre: "Vela sobre los hombros",
    sanscrito: "Salamba Sarvangasana",
    familia: "invertida",
    segundos: 90,
    minimo: 45,
    maximo: 180,
    nivel: 3,
    carga: 3,
    estilos: ["hatha", "iyengar", "ashtanga"],
    objetivos: ["piernas", "calma", "foco"],
    trabaja:
      "Inversión completa apoyada en los hombros. Es potente y también la postura con más lesiones cervicales descritas: sin mantas bajo los hombros, todo el peso cae en la nuca.",
    como: [
      "Dobla dos o tres mantas y apoya los hombros en el borde; la cabeza queda más abajo, en el suelo.",
      "Sube las piernas y sostén la espalda con las manos.",
      "El peso va en los hombros y los codos, nunca en el cuello.",
      "No gires la cabeza mientras estás arriba. Baja vértebra por vértebra.",
    ],
    cuidado: "Si nunca la has hecho, apréndela con alguien al lado. No es una postura para aprender sola desde una pantalla.",
    necesita: ["manta"],
    evita: [
      "cuello",
      "hombros",
      "glaucoma",
      "hipertension",
      "embarazo",
      "menstruacion",
      "osteoporosis",
      "vertigo",
      "cirugia",
    ],
    masFacil: "Haz piernas en la pared: casi todo lo bueno, nada del riesgo.",
    soloAvanzada: true,
    prepararCon: ["ext-puente"],
    prioridad: 8,
    figura: "vela_hombros",
    fuente: "Lesiones cervicales por sarvangasana — biblioteca, carpeta yoga/seguridad_lesiones",
  },

  // ══ Bajar ══════════════════════════════════════════════════
  {
    id: "enf-rodillas-pecho",
    fase: "enfriamiento",
    nombre: "Rodillas al pecho",
    sanscrito: "Apanasana",
    familia: "supina",
    segundos: 50,
    minimo: 35,
    maximo: 90,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "restaurativo", "somatico"],
    objetivos: ["espalda", "digestion", "calma", "menstrual"],
    trabaja: "Suelta la espalda baja después de las extensiones y masajea suave el vientre con el movimiento.",
    como: [
      "Acostada, abraza las dos rodillas hacia el pecho.",
      "Mécete un poco de lado a lado y adelante y atrás.",
      "Si el vientre molesta, separa un poco las rodillas.",
    ],
    evita: ["embarazo"],
    prioridad: 1,
    figura: "rodillas_pecho",
  },
  {
    id: "enf-banana",
    fase: "enfriamiento",
    nombre: "Media luna acostada",
    sanscrito: "Bananasana",
    familia: "supina",
    segundos: 90,
    minimo: 60,
    maximo: 180,
    porLado: true,
    nivel: 1,
    carga: 1,
    estilos: ["yin", "restaurativo"],
    objetivos: ["cuello_hombros", "calma", "pecho", "espalda"],
    trabaja:
      "Estira todo el costado del cuerpo, incluido el cuadrado lumbar y los intercostales, con el cuerpo entero apoyado.",
    como: [
      "Acostada, camina los pies y los brazos hacia la derecha, sin girar la pelvis.",
      "El cuerpo dibuja una luna con la panza mirando al techo.",
      "Cruza los tobillos o toma la muñeca si quieres más.",
      "Cambia de lado.",
    ],
    evita: ["embarazo"],
    prioridad: 4,
    figura: "banana",
  },
  {
    id: "enf-piernas-silla",
    fase: "enfriamiento",
    nombre: "Pantorrillas en la silla",
    familia: "supina",
    segundos: 180,
    minimo: 90,
    maximo: 360,
    nivel: 1,
    carga: 1,
    estilos: ["restaurativo", "silla"],
    objetivos: ["piernas", "espalda", "calma", "dormir"],
    trabaja:
      "Deja la cadera y la rodilla en noventa grados, que es la posición donde la espalda baja suelta del todo. Sirve cuando la pared no es opción.",
    como: [
      "Acuéstate en el suelo con una silla a los pies.",
      "Sube las pantorrillas al asiento; las rodillas quedan sobre las caderas.",
      "Manta bajo la cabeza. Quédate y respira lento.",
    ],
    necesita: ["silla"],
    mejoraCon: ["manta"],
    evita: ["embarazo"],
    prioridad: 3,
    figura: "pantorrillas_silla",
  },
];
