import type { Paso } from "./tipos";

/* Respiración, llegada, savasana y meditación.

   Van aparte de las posturas porque se rigen por otras reglas: acá no hay
   alineación que cuidar, pero sí contraindicaciones propias. Las dos que de
   verdad importan:

   · Las respiraciones rápidas y con retención (kapalabhati, bhastrika, retener
     con los pulmones llenos) quedan fuera en embarazo, presión alta, glaucoma
     y problemas de corazón. Suben la presión intratorácica y la presión
     arterial durante la práctica.
   · Alargar la exhalación es la parte con más respaldo: respirar lento, con la
     salida más larga que la entrada, aumenta el tono vagal. De ahí sale la
     regla del 4-6 y del 4-7-8.

   Los artículos de respaldo están en biblioteca-cientifica/yoga/pranayama y
   yoga/meditacion_mindfulness. */

export const RESPIRACIONES: Paso[] = [
  // ══ Llegar ═════════════════════════════════════════════════
  {
    id: "cen-llegar",
    fase: "centrado",
    nombre: "Llegar",
    familia: "quietud",
    segundos: 60,
    minimo: 40,
    maximo: 120,
    nivel: 1,
    carga: 1,
    estilos: [],
    objetivos: [],
    trabaja:
      "El primer minuto no es trámite: es donde el cuerpo pasa de andar haciendo cosas a estar en una sola. Sin esto la práctica empieza apurada y termina apurada.",
    como: [
      "Siéntate cómoda, sobre una manta doblada si la espalda se redondea.",
      "Cierra los ojos o baja la mirada.",
      "Nota tres cosas: dónde te apoyas, cómo está tu respiración ahora, y qué parte del cuerpo pide algo hoy.",
      "No cambies nada todavía. Solo mira.",
    ],
    mejoraCon: ["manta", "bloque", "silla"],
    base: true,
    prioridad: 0,
    figura: "sentada",
  },
  {
    id: "cen-intencion",
    fase: "centrado",
    nombre: "Para qué es esto hoy",
    familia: "quietud",
    segundos: 40,
    minimo: 30,
    maximo: 60,
    nivel: 1,
    carga: 1,
    estilos: ["kundalini", "hatha"],
    objetivos: ["foco", "calma"],
    trabaja:
      "Nombrar para qué estás practicando cambia lo que haces en las posturas difíciles: deja de ser una competencia con el cuerpo.",
    como: [
      "Piensa una frase corta para hoy. «Bajar un cambio». «Soltar los hombros».",
      "No tiene que ser profunda. Tiene que ser tuya.",
      "Vuelve a ella cuando la práctica se ponga incómoda.",
    ],
    soloPrimeraVez: false,
    prioridad: 1,
    figura: "sentada",
  },
  {
    id: "cen-postura-sentada",
    fase: "centrado",
    nombre: "Cómo sentarse",
    familia: "quietud",
    segundos: 60,
    minimo: 45,
    maximo: 90,
    nivel: 1,
    carga: 1,
    estilos: ["iyengar"],
    objetivos: [],
    trabaja:
      "Si las rodillas quedan más arriba que las caderas, la pelvis se va hacia atrás y la espalda se redondea sola. Subirse a una manta arregla eso antes de que empiece a doler.",
    como: [
      "Siéntate en el borde de una manta doblada o un cojín firme.",
      "Las rodillas tienen que quedar más abajo que las caderas.",
      "Si igual cuesta, siéntate en una silla con los pies en el suelo.",
      "Manos en los muslos, hombros sueltos.",
    ],
    mejoraCon: ["manta", "bloque", "silla"],
    soloPrimeraVez: true,
    prioridad: 1,
    figura: "sentada",
  },

  // ══ Respiración de entrada ═════════════════════════════════
  {
    id: "res-observar",
    fase: "respiracion",
    nombre: "Mirar la respiración",
    familia: "respiracion",
    segundos: 75,
    minimo: 45,
    maximo: 150,
    nivel: 1,
    carga: 1,
    estilos: [],
    objetivos: ["calma", "foco"],
    trabaja:
      "Antes de cambiar la respiración hay que saber cómo está. Casi siempre está más arriba y más corta de lo que uno cree.",
    como: [
      "Una mano en el pecho, la otra en el vientre.",
      "No cambies nada: solo nota cuál mano se mueve más.",
      "Cuenta cuánto dura tu entrada y cuánto tu salida.",
      "Si la de arriba se mueve más, tu respiración está alta. Eso pasa con el estrés.",
    ],
    base: true,
    prioridad: 1,
    figura: "respirar_sentada",
  },
  {
    id: "res-diafragma",
    fase: "respiracion",
    nombre: "Respiración al vientre",
    sanscrito: "Respiración diafragmática",
    familia: "respiracion",
    segundos: 120,
    minimo: 60,
    maximo: 240,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "somatico", "restaurativo"],
    objetivos: ["calma", "dormir", "foco", "embarazo"],
    trabaja:
      "Usar el diafragma en vez del cuello y el pecho. Es la base de todo lo demás: sin esto, las respiraciones más elaboradas se hacen con los músculos equivocados.",
    como: [
      "Mano en el vientre, bajo el ombligo.",
      "Inhala por la nariz dejando que el vientre se infle contra la mano.",
      "Exhala y deja que baje solo, sin empujar.",
      "Diez respiraciones así, sin apurar.",
    ],
    respirar: "Todo por la nariz, entrada y salida.",
    prioridad: 1,
    figura: "respirar_sentada",
  },
  {
    id: "res-46",
    fase: "respiracion",
    nombre: "Respiración 4-6",
    familia: "respiracion",
    segundos: 150,
    minimo: 90,
    maximo: 300,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "somatico"],
    objetivos: ["calma", "dormir", "foco", "menstrual"],
    trabaja:
      "Exhalación más larga que la inhalación, a un ritmo de unas seis respiraciones por minuto. Es el patrón con más respaldo para subir la variabilidad del pulso, que es la medida de cuánto manda el sistema de reposo.",
    como: [
      "Inhala contando hasta cuatro.",
      "Exhala contando hasta seis, sin apretar el final.",
      "Si te falta aire, baja a 3-4 y mantén la proporción.",
      "Sigue de dos a cinco minutos.",
    ],
    respirar: "Por la nariz. Que la cuenta sea cómoda, no una prueba.",
    prioridad: 2,
    figura: "respirar_sentada",
    fuente: "Respiración lenta y tono vagal — biblioteca, carpeta yoga/pranayama",
  },
  {
    id: "res-nadi",
    fase: "respiracion",
    nombre: "Respiración alterna",
    sanscrito: "Nadi Shodhana",
    familia: "respiracion",
    segundos: 180,
    minimo: 90,
    maximo: 300,
    nivel: 2,
    carga: 1,
    estilos: ["hatha", "kundalini", "iyengar"],
    objetivos: ["calma", "foco"],
    trabaja:
      "Alternar la fosa nasal por la que entra el aire. Obliga a que la respiración sea lenta y pareja, y da algo concreto en que sostener la atención.",
    como: [
      "Pulgar derecho en la fosa derecha, anular en la izquierda.",
      "Cierra la derecha, inhala por la izquierda.",
      "Cierra la izquierda, abre la derecha y exhala por ahí.",
      "Inhala por la derecha, cambia, exhala por la izquierda. Ese es un ciclo.",
      "Haz de cinco a diez ciclos, terminando por la izquierda.",
    ],
    cuidado: "Nada de retener el aire hasta que la parte de respirar alterna te salga sola.",
    evita: ["embarazo"],
    prioridad: 3,
    figura: "respirar_sentada",
  },
  {
    id: "res-fuego",
    fase: "respiracion",
    nombre: "Respiración de fuego",
    sanscrito: "Kapalabhati",
    familia: "respiracion",
    segundos: 90,
    minimo: 60,
    maximo: 150,
    nivel: 3,
    carga: 3,
    estilos: ["kundalini", "ashtanga"],
    objetivos: ["energia", "foco", "digestion"],
    trabaja:
      "Exhalaciones cortas y activas empujando con el abdomen; la inhalación entra sola. Sube el pulso y la presión durante la práctica: por eso queda fuera en varios casos.",
    como: [
      "Sentada con la espalda larga, una mano en el vientre.",
      "Exhala corto y fuerte por la nariz metiendo el ombligo.",
      "Deja que la inhalación entre sola, sin ayudarla.",
      "Unas veinte a treinta veces, descansa, y repite si te sientes bien.",
    ],
    cuidado:
      "Si te mareas, paras y respiras normal. No es algo que haya que aguantar. Nunca la hagas con el estómago lleno.",
    evita: ["embarazo", "hipertension", "glaucoma", "vertigo", "cirugia", "menstruacion"],
    masFacil: "Si te marea, haz solo exhalaciones largas por la boca: despierta sin acelerar.",
    soloMomento: ["manana", "dia"],
    prioridad: 5,
    figura: "respirar_sentada",
    fuente: "Efectos agudos de kapalabhati — biblioteca, carpeta yoga/pranayama",
  },
  {
    id: "res-ujjayi",
    fase: "respiracion",
    nombre: "Respiración del mar",
    sanscrito: "Ujjayi",
    familia: "respiracion",
    segundos: 90,
    minimo: 60,
    maximo: 150,
    nivel: 2,
    carga: 1,
    estilos: ["vinyasa", "ashtanga"],
    objetivos: ["foco", "energia"],
    trabaja:
      "Estrechar apenas la glotis alarga la respiración y la vuelve audible. En vinyasa marca el ritmo: mientras se escuche pareja, el ritmo es sostenible.",
    como: [
      "Inhala por la nariz y exhala por la boca abierta, como empañando un vidrio.",
      "Repite eso mismo pero con la boca cerrada: el sonido queda en la garganta.",
      "Entrada y salida del mismo largo.",
      "Ese sonido te va a acompañar toda la práctica movida.",
    ],
    cuidado: "Si aparece tensión en la mandíbula o en el cuello, es demasiado apretado.",
    soloPrimeraVez: false,
    prioridad: 4,
    figura: "respirar_sentada",
  },
  {
    id: "res-brazos-kundalini",
    fase: "respiracion",
    nombre: "Brazos arriba con respiración",
    familia: "respiracion",
    segundos: 90,
    minimo: 60,
    maximo: 150,
    nivel: 2,
    carga: 2,
    estilos: ["kundalini"],
    objetivos: ["energia", "cuello_hombros", "foco"],
    trabaja:
      "Sostener los brazos arriba mientras se respira rápido es el formato típico de kundalini: la incomodidad es parte del ejercicio y se trabaja respirando, no aflojando.",
    como: [
      "Sentada, sube los brazos en V, pulgares hacia arriba.",
      "Respira rápido y parejo por la nariz, o respira largo si prefieres.",
      "Un minuto. Los brazos van a arder; sigue respirando.",
      "Al terminar, inhala, retén un momento y suelta los brazos.",
    ],
    evita: ["hombros", "hipertension", "embarazo", "cuello"],
    prioridad: 6,
    figura: "brazos_arriba_sentada",
  },

  // ══ Respiración de cierre ══════════════════════════════════
  {
    id: "fin-478",
    fase: "respiracion_final",
    nombre: "Respiración 4-7-8",
    familia: "respiracion",
    segundos: 120,
    minimo: 75,
    maximo: 200,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "nidra"],
    objetivos: ["dormir", "calma"],
    trabaja:
      "Exhalación muy larga con una retención corta. Es la versión más conocida para antes de dormir; lo que hace el trabajo es que la salida dure más del doble que la entrada.",
    como: [
      "Inhala por la nariz contando hasta cuatro.",
      "Retén el aire contando hasta siete.",
      "Exhala por la boca contando hasta ocho, con sonido.",
      "Cuatro rondas. No más al principio.",
    ],
    cuidado: "Si la retención te angustia, sáltala: inhala en cuatro y exhala en ocho. Funciona igual.",
    evita: ["embarazo", "hipertension"],
    soloMomento: ["noche"],
    prioridad: 2,
    figura: "respirar_sentada",
  },
  {
    id: "fin-bhramari",
    fase: "respiracion_final",
    nombre: "Respiración del zumbido",
    sanscrito: "Bhramari",
    familia: "respiracion",
    segundos: 90,
    minimo: 60,
    maximo: 150,
    nivel: 1,
    carga: 1,
    estilos: ["hatha", "kundalini"],
    objetivos: ["calma", "dormir", "foco"],
    trabaja:
      "Zumbar al exhalar alarga la salida sola y la vibración se siente en la cara y el cráneo. Es de las prácticas más fáciles de sostener cuando la cabeza no para.",
    como: [
      "Tapa suave los oídos con los pulgares o con los dedos índices.",
      "Inhala por la nariz.",
      "Exhala zumbando con la boca cerrada, como una abeja, hasta el final del aire.",
      "Cinco a diez veces. Escucha el zumbido por dentro.",
    ],
    prioridad: 3,
    figura: "respirar_sentada",
  },
  {
    id: "fin-exhalar-largo",
    fase: "respiracion_final",
    nombre: "Exhalar largo",
    familia: "respiracion",
    segundos: 90,
    minimo: 60,
    maximo: 180,
    nivel: 1,
    carga: 1,
    estilos: [],
    objetivos: ["calma", "dormir", "menstrual"],
    trabaja:
      "Lo mismo que el 4-6 pero sin contar: solo dejar que la salida dure más. Sirve cuando contar pone nerviosa.",
    como: [
      "Inhala normal por la nariz.",
      "Exhala más lento de lo que te salga solo, por la nariz o la boca.",
      "Sin números. Solo que la salida sea la parte larga.",
      "Diez respiraciones.",
    ],
    prioridad: 2,
    figura: "respirar_sentada",
  },

  // ══ Savasana ═══════════════════════════════════════════════
  {
    id: "sav-normal",
    fase: "savasana",
    nombre: "Savasana",
    sanscrito: "Postura del cadáver",
    familia: "quietud",
    segundos: 240,
    minimo: 120,
    maximo: 600,
    nivel: 1,
    carga: 1,
    estilos: [],
    objetivos: [],
    trabaja:
      "No es el relleno del final: es donde el cuerpo integra lo que acaba de pasar. Saltársela es lo más común y lo que más se nota.",
    como: [
      "Acostada boca arriba, piernas separadas, pies caídos hacia afuera.",
      "Brazos a los lados, palmas hacia arriba.",
      "Manta enrollada bajo las rodillas si la espalda baja molesta.",
      "Deja que el cuerpo pese. No hay nada que hacer acá.",
    ],
    mejoraCon: ["manta", "bolster"],
    evita: ["embarazo"],
    base: true,
    prioridad: 0,
    figura: "savasana",
  },
  {
    id: "sav-lateral",
    fase: "savasana",
    nombre: "Descanso de lado",
    familia: "quietud",
    segundos: 240,
    minimo: 120,
    maximo: 600,
    nivel: 1,
    carga: 1,
    estilos: [],
    objetivos: ["embarazo"],
    trabaja:
      "El descanso final del embarazo se hace de lado izquierdo, no de espaldas: acostada boca arriba, el útero puede comprimir la vena cava y bajar el retorno de sangre al corazón.",
    como: [
      "Acuéstate sobre el lado izquierdo.",
      "Un cojín o almohada entre las rodillas y otra bajo la cabeza.",
      "Una almohada más para abrazar adelante si quieres.",
      "Quédate hasta que la respiración se haga larga sola.",
    ],
    mejoraCon: ["bolster", "manta"],
    soloCuidados: ["embarazo"],
    base: true,
    prioridad: 0,
    figura: "savasana_lateral",
    fuente: "Posición supina en el embarazo — biblioteca, carpeta yoga/embarazo",
  },
  {
    id: "sav-nidra",
    fase: "savasana",
    nombre: "Recorrido del cuerpo",
    sanscrito: "Yoga nidra",
    familia: "quietud",
    segundos: 420,
    minimo: 300,
    maximo: 900,
    nivel: 1,
    carga: 1,
    estilos: ["nidra", "restaurativo"],
    objetivos: ["dormir", "calma"],
    trabaja:
      "Recorrer el cuerpo parte por parte, en un orden fijo, sin moverse. La consigna es quedarse justo en el borde del sueño, despierta pero muy quieta.",
    como: [
      "Acostada y tapada: el cuerpo quieto se enfría.",
      "Lleva la atención a la mano derecha, dedo por dedo. Después el brazo, el hombro.",
      "Sigue por el lado izquierdo, después las piernas, la espalda, la cara.",
      "Termina sintiendo el cuerpo entero a la vez y quédate ahí.",
      "Si te duermes, no pasa nada.",
    ],
    mejoraCon: ["manta", "bolster"],
    evita: ["embarazo"],
    soloMomento: ["noche", "dia"],
    prioridad: 4,
    figura: "nidra",
  },

  // ══ Meditación ═════════════════════════════════════════════
  {
    id: "med-respiracion",
    fase: "meditacion",
    nombre: "Meditación en la respiración",
    familia: "quietud",
    segundos: 300,
    minimo: 120,
    maximo: 900,
    nivel: 1,
    carga: 1,
    estilos: [],
    objetivos: ["calma", "foco"],
    trabaja:
      "La más simple y la más estudiada: sostener la atención en la respiración y volver cada vez que se va. Volver ES la práctica, no el fracaso de la práctica.",
    como: [
      "Sentada cómoda, espalda larga, ojos cerrados.",
      "Pon la atención donde más sientas el aire: nariz, pecho o vientre.",
      "Cuando te des cuenta de que estás pensando en otra cosa, vuelve. Sin reto.",
      "Eso se va a repetir muchas veces. Está bien.",
    ],
    mejoraCon: ["manta", "silla"],
    prioridad: 2,
    figura: "sentada",
  },
  {
    id: "med-cuerpo",
    fase: "meditacion",
    nombre: "Recorrido corto del cuerpo",
    familia: "quietud",
    segundos: 240,
    minimo: 120,
    maximo: 600,
    nivel: 1,
    carga: 1,
    estilos: ["somatico", "nidra"],
    objetivos: ["calma", "dormir", "foco"],
    trabaja: "Pasar la atención por el cuerpo de a poco. Sirve cuando la cabeza está demasiado activa para quedarse en la respiración.",
    como: [
      "Empieza por los pies y sube lentamente.",
      "En cada parte, nota solo lo que hay: temperatura, peso, contacto, o nada.",
      "No hay que relajar nada a propósito.",
      "Termina en la cara y la mandíbula, que es donde más se guarda.",
    ],
    prioridad: 3,
    figura: "sentada",
  },
  {
    id: "med-mantra",
    fase: "meditacion",
    nombre: "Meditación con mantra",
    familia: "quietud",
    segundos: 300,
    minimo: 150,
    maximo: 600,
    nivel: 1,
    carga: 1,
    estilos: ["kundalini", "hatha"],
    objetivos: ["calma", "foco"],
    trabaja:
      "Repetir una palabra o un sonido da a la atención algo más concreto que la respiración. La palabra puede ser sánscrita o no: el mecanismo es el mismo.",
    como: [
      "Elige una palabra corta. «So» al inhalar, «ham» al exhalar, o una tuya.",
      "Repítela en silencio, al ritmo de la respiración.",
      "Cuando se te pierda, vuelve a empezar.",
    ],
    prioridad: 4,
    figura: "sentada",
  },
];
